import { randomBytes, createHash } from "node:crypto";
import { expect, test } from "@playwright/test";
import { createOnboardedAccount } from "./helpers/auth";
import { hasDb, dbQuery } from "./helpers/db";

test("독립 트레이너 이용권·초대 수락·공유 설정·연결 삭제", async ({ page, browser }) => {
  test.skip(!hasDb, "needs DB fixtures");
  // Never send messages to test phone numbers when a real provider is configured.
  test.skip(Boolean(process.env.SOLAPI_API_KEY), "requires messaging to be unconfigured");
  test.setTimeout(150_000);
  const trainerEmail = await createOnboardedAccount(page);
  await page.goto("/home");
  const grid = page.getByRole("navigation", { name: "앱", exact: true });
  await expect(grid.getByRole("link", { name: "헬스 트레이너", exact: true })).toHaveCount(0);
  await grid.getByRole("button", { name: "편집", exact: true }).click();
  await grid.getByRole("button", { name: "앱 추가", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "앱 추가", exact: true }).getByRole("link", { name: "트레이너 대시보드", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "앱 추가 닫기", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "앱 추가", exact: true })).toHaveCount(0);
  await page.waitForFunction(() => !window.history.state?.heltchModal);
  await page.goto("/settings/trainer-pass");
  await page.getByLabel("트레이너 이름", { exact: true }).fill("검증 트레이너");
  await page.getByLabel("알림 받을 휴대폰 번호", { exact: true }).fill("01012345678");
  await page.getByRole("button", { name: "등록 신청", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("신청했어요");
  await page.goto("/trainer");
  await expect(page).toHaveURL(/\/settings\/trainer-pass$/);
  await dbQuery("update pt_passes set status='active',starts_on=(now() at time zone 'Asia/Seoul')::date-1,ends_on='infinity'::date where trainer_id=(select id from auth.users where email=$1)", [trainerEmail]);
  await page.goto("/home");
  await expect(grid.getByRole("link", { name: "헬스 트레이너", exact: true })).toBeVisible();
  await grid.getByRole("button", { name: "편집", exact: true }).click();
  await grid.getByRole("button", { name: "헬스 트레이너 숨기기", exact: true }).click();
  await grid.getByRole("button", { name: "앱 추가", exact: true }).click();
  await page.getByRole("dialog", { name: "앱 추가", exact: true }).getByRole("link", { name: "트레이너 대시보드", exact: true }).click();
  await expect(page).toHaveURL(/\/trainer$/);
  await page.goto("/home");
  await expect(grid.getByRole("link", { name: "헬스 트레이너", exact: true })).toBeVisible();
  await grid.getByRole("button", { name: "편집", exact: true }).click();
  await grid.getByRole("button", { name: "앱 추가", exact: true }).click();
  await page.getByRole("dialog", { name: "앱 추가", exact: true }).getByRole("link", { name: "트레이너 대시보드", exact: true }).click();
  await expect(page.getByRole("heading", { name: "담당 회원 · 0명", exact: true })).toBeVisible();
  await page.goto("/settings/trainer-pass");
  await expect(page.getByText(/무제한 · 회원 15명/)).toBeVisible();
  await page.goto("/trainer");
  // Create only the invitation fixture: the test never invokes a real send endpoint.
  const token = randomBytes(32).toString("hex");
  const baseUrl = process.env.E2E_BASE_URL ?? "http://127.0.0.1:3000";
  await dbQuery("insert into pt_invites(trainer_id,token_hash,phone) select id,$2,'01087654321' from auth.users where email=$1", [trainerEmail,createHash("sha256").update(token).digest("hex")]);
  const memberContext = await browser.newContext();
  try {
    const member = await memberContext.newPage();
    const memberEmail = await createOnboardedAccount(member);
    await member.goto(`${baseUrl}/trainer/invite/${token}`);
    await member.getByLabel("운동 기록 (일수·세트·시간)", { exact: true }).check();
    await member.getByLabel("이 트레이너의 관리를 받는 데 동의합니다.", { exact: true }).check();
    await member.getByRole("button", { name: "동의하고 연결", exact: true }).click();
    await expect(member).toHaveURL(/\/settings\/trainers$/);
    await expect(member.getByRole("heading", { name: "검증 트레이너", exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByRole("heading", { name: "담당 회원 · 1명", exact: true })).toBeVisible();
    await expect(page.getByText("비공개", { exact: true })).toHaveCount(2);
    await page.getByRole("link", { name: "회원 통계 · 운동 처방", exact: true }).click();
    await page.getByRole("link", { name: "운동 통계", exact: true }).click();
    await expect(page.getByRole("heading", { name: "통계 요약", exact: true })).toBeVisible();
    await expect(page.getByText("아직 완료한 운동이 없어요", { exact: true })).toBeVisible();
    await page.getByRole("link", { name: "월간", exact: true }).click();
    await expect(page).toHaveURL(/view=stats&period=month/);
    await page.getByRole("link", { name: "연간", exact: true }).click();
    await expect(page.getByRole("heading", { name: "월별 운동 추이", exact: true })).toBeVisible();
    await page.getByText("날짜별 상세 기록", { exact: true }).click();
    await expect(page.getByText("01", { exact: true })).toBeVisible();
    await page.getByRole("link", { name: "운동 처방", exact: true }).click();
    await expect(page.getByText("회원이 운동 처방을 허용하지 않았어요.", { exact: false })).toBeVisible();
    await dbQuery("insert into routine_exercises(user_id,focus,exercise_id,equipment,day_index,sets,reps) select id,'chest','bench-press','barbell',0,3,10 from auth.users where email=$1", [memberEmail]);
    await dbQuery("insert into routine_exercises(user_id,focus,exercise_id,equipment,day_index,sets,reps) select id,'lower','squat','barbell',1,3,10 from auth.users where email=$1", [memberEmail]);
    await member.getByLabel("운동 처방 허용", { exact: true }).check();
    await member.getByRole("button", { name: "공유 설정 저장", exact: true }).click();
    await expect(member.getByRole("status")).toHaveText("저장했어요.");
    await page.reload();
    const permanent = page.getByRole("region", { name: "운동 처방 · 영구 루틴", exact: true });
    await permanent.getByLabel("처방 운동 찾기").fill("스쿼트");
    await expect(permanent.locator("details")).toHaveCount(1);
    await expect(permanent.getByRole("heading", {name:"스쿼트",exact:true})).toBeVisible();
    await permanent.getByLabel("처방 운동 찾기").fill("없는운동xyz");
    await expect(permanent.getByRole("status")).toContainText("일치하는 운동이 없어요");
    await permanent.getByLabel("처방 운동 찾기").fill("");
    await expect(permanent.locator("details")).toHaveCount(2);
    await expect(permanent.locator("details").nth(0)).toHaveAttribute("open", "");
    await expect(permanent.locator("details").nth(1)).not.toHaveAttribute("open");
    await permanent.locator("summary").nth(1).click();
    await expect(permanent.locator("details").nth(1).getByRole("button", { name: "운동 변경", exact: true })).toBeVisible();
    await permanent.locator("summary").nth(1).click();
    await page.getByRole("link", { name: "오늘만", exact: true }).click();
    await expect(page.getByRole("heading", { name: "운동 처방 · 오늘만", exact: true })).toBeVisible();
    await expect(permanent).toHaveCount(0);
    await page.getByRole("link", { name: "영구 루틴", exact: true }).click();
    await permanent.locator("details").first().getByRole("button", { name: "운동 변경", exact: true }).click();
    await expect(permanent.getByLabel("세트", { exact: true })).toHaveValue("3");
    await permanent.getByLabel("세트", { exact: true }).fill("4");
    await permanent.getByRole("button", { name: "변경 내용 확인", exact: true }).click();
    await permanent.getByRole("button", { name: "처방 저장", exact: true }).click();
    await expect(permanent.getByText("4세트 × 10회", { exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({path:"scripts/.verify-shots/trainer-prescription-layout.png",fullPage:true});
    await dbQuery("insert into exercise_completions(user_id,for_date,exercise_row_id,status,exercise_id,equipment,sets,reps,weight_kg,focus) select user_id,(now() at time zone 'Asia/Seoul')::date,id,'done',exercise_id,equipment,3,10,20,focus from routine_exercises where user_id=(select id from auth.users where email=$1) and day_index=0", [memberEmail]);
    await page.getByRole("link", { name: "운동 통계", exact: true }).click();
    await expect(page.getByRole("heading", { name: "통계 요약", exact: true })).toBeVisible();
    await expect(page.getByText("1일 동안 3세트를 완료했어요", { exact: true })).toBeVisible();
    await expect(page.getByLabel("기간별 완료 세트 그래프", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "볼륨", exact: true }).click();
    await expect(page.getByLabel("기간별 볼륨 그래프", {exact:true})).toBeVisible();
    await page.getByRole("button", { name: /600kg$/ }).click();
    await expect(page.getByRole("button", {name:/600kg$/})).toHaveAttribute("aria-pressed","true");
    await page.getByRole("button", { name: "운동 시간", exact: true }).click();
    await expect(page.getByText("이 기간에는 운동 시간 기록이 없어요.",{exact:true})).toBeVisible();
    await page.getByRole("button", { name: "완료 세트", exact: true }).click();
    await page.screenshot({path:"scripts/.verify-shots/trainer-statistics-layout.png",fullPage:true});
    await page.emulateMedia({colorScheme:"light"});
    await page.evaluate(() => document.documentElement.classList.remove("dark"));
    await page.screenshot({path:"scripts/.verify-shots/trainer-statistics-light.png",fullPage:true});
    await page.setViewportSize({width:1280,height:900});
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({path:"scripts/.verify-shots/trainer-statistics-desktop.png",fullPage:true});
    await page.setViewportSize({width:393,height:852});
    await page.emulateMedia({colorScheme:"dark"});
    await page.evaluate(() => document.documentElement.classList.add("dark"));
    await page.getByRole("link", { name: "운동 처방", exact: true }).click();
    await member.getByLabel("운동 처방 허용", { exact: true }).uncheck();
    await member.getByRole("button", { name: "공유 설정 저장", exact: true }).click();
    await expect(member.getByRole("status")).toHaveText("저장했어요.");
    await page.reload();
    await expect(permanent).toHaveCount(0);
    await page.goto("/trainer");
    await member.goto(`${baseUrl}/settings/trainers`);
    await member.getByLabel("운동 기록 (일수·세트·시간)", { exact: true }).uncheck();
    await member.getByRole("button", { name: "공유 설정 저장", exact: true }).click();
    await expect(member.getByRole("status")).toHaveText("저장했어요.");
    await page.reload();
    await expect(page.getByText("비공개", { exact: true })).toHaveCount(3);
    await member.getByText("트레이너 연결 삭제", { exact: true }).click();
    await member.getByLabel("이 트레이너의 관리 권한을 해제합니다.", { exact: true }).check();
    await member.getByRole("button", { name: "연결 삭제", exact: true }).click();
    await expect(member.getByText("연결된 트레이너가 없어요.", { exact: false })).toBeVisible();
    await expect(member.getByRole("heading", { name: "연결 삭제 알림", exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByRole("heading", { name: "담당 회원 · 0명", exact: true })).toBeVisible();
    await member.goto(`${baseUrl}/trainer/invite/${token}`);
    await expect(member.getByText("만료되었거나 이미 사용한 초대예요.", { exact: false })).toBeVisible();
  } finally { await memberContext.close(); }
});