import {test,expect} from "@playwright/test";
import {createOnboardedAccount} from "./helpers/auth";
import {dbQuery,hasDb} from "./helpers/db";
test("개인화 추천: 선호 저장·성별보다 우선·미리보기·명시적 적용",async({page})=>{
 test.skip(!hasDb,"requires DB fixtures");test.setTimeout(150_000);
 const email=await createOnboardedAccount(page);
 await dbQuery("update profiles set gender='female',experience='intermediate',goal='muscle_gain' where user_id=(select id from auth.users where email=$1)",[email]);
 await page.goto("/settings/routine");
 const panel=page.getByRole("region",{name:/주 .*루틴/});
 await expect(panel.getByRole("heading",{name:/하체 중심/})).toBeVisible();
 await panel.getByText("추천 선호 조정",{exact:true}).click();
 await panel.getByLabel("주당 운동 횟수",{exact:true}).selectOption("2");
 await panel.getByLabel("집중 부위",{exact:true}).selectOption("upper");
 await panel.getByLabel("선호 기구",{exact:true}).selectOption("machine");
 await panel.getByLabel("추천 운동 시간",{exact:true}).selectOption("30");
 await expect(panel.getByRole("button",{name:"이 추천으로 적용",exact:true})).toBeDisabled();
 await panel.getByRole("button",{name:"선호 저장하고 추천 갱신",exact:true}).click();
 await expect(panel.getByRole("heading",{name:"주 2회 · 상체 중심 루틴",exact:true})).toBeVisible();
 await expect(panel.getByText("직접 저장한 선호를 성별 기본값보다 우선해요.",{exact:true})).toBeVisible();
 await page.reload();
 await expect(panel.getByRole("heading",{name:"주 2회 · 상체 중심 루틴",exact:true})).toBeVisible();
 await panel.getByRole("button",{name:"이 추천으로 적용",exact:true}).click();
 await expect(panel.getByText("기준 루틴을 위 7일 구성으로 바꿀까요?",{exact:false})).toBeVisible();
 await panel.getByRole("button",{name:"취소",exact:true}).click();
 const before=await dbQuery<{variant_id:string}>("select variant_id from user_routines where user_id=(select id from auth.users where email=$1)",[email]);
 expect(before[0].variant_id).not.toBe("custom");
 await page.screenshot({path:"scripts/.verify-shots/personal-recommendation.png",fullPage:true});
 await panel.getByRole("button",{name:"이 추천으로 적용",exact:true}).click();
 await panel.getByRole("button",{name:"확인하고 루틴 적용",exact:true}).click();
 await expect(page).toHaveURL(url => url.pathname === "/routine");
 const saved=await dbQuery<{custom_week:string[][]}>("select custom_week from user_routines where user_id=(select id from auth.users where email=$1)",[email]);
 expect(saved[0].custom_week.filter(blocks=>!blocks.includes("rest"))).toHaveLength(2);
 const rows=await dbQuery<{equipment:string;count:number}>("select equipment,count(*)::int as count from routine_exercises where user_id=(select id from auth.users where email=$1) group by equipment",[email]);
 expect(rows.reduce((sum,row)=>sum+row.count,0)).toBe(4);
 expect(rows.every(row=>["machine","cable","smith"].includes(row.equipment))).toBe(true);
 await page.goto("/plan");
 await expect(page.getByRole("link",{name:"추천 선호 조정",exact:true})).toBeVisible();
 const permanentBefore=await dbQuery("select id,exercise_id,equipment,sets,reps from routine_exercises where user_id=(select id from auth.users where email=$1) order by id",[email]);
 await page.goto("/plan/today?focus=chest");
 const main=page.locator("section").filter({has:page.getByRole("heading",{name:"본운동",exact:true})});
 await main.getByRole("button",{name:"추천으로 채우기",exact:true}).click();
 if(await page.getByRole("button",{name:"교체하기",exact:true}).isVisible()) await page.getByRole("button",{name:"교체하기",exact:true}).click();
 await expect(main.getByLabel("기구",{exact:true})).toHaveCount(2);
 await main.getByRole("button",{name:"저장",exact:true}).click();
 await expect(main.getByText("저장됨",{exact:true})).toBeVisible();
 const permanentAfter=await dbQuery("select id,exercise_id,equipment,sets,reps from routine_exercises where user_id=(select id from auth.users where email=$1) order by id",[email]);
 expect(permanentAfter).toEqual(permanentBefore);
 const todayRows=await dbQuery<{equipment:string}>("select equipment from daily_plan where user_id=(select id from auth.users where email=$1) and for_date=(now() at time zone 'Asia/Seoul')::date and focus='chest'",[email]);
 expect(todayRows).toHaveLength(2);
 expect(todayRows.every(row=>['machine','cable','smith'].includes(row.equipment))).toBe(true);
});