import { expect, test } from "@playwright/test";
import { createOnboardedAccount } from "./helpers/auth";
import { dbQuery, hasDb } from "./helpers/db";
test("구간 편집·전환·반복·일시정지와 복원 후 중복 없이 저장", async ({ page }, info) => {
 test.skip(!hasDb, "DB required"); test.setTimeout(180000);
 const email = await createOnboardedAccount(page);
 await page.goto("/routine/running-intervals", { waitUntil: "networkidle" });
 await expect(page.locator(".app-splash")).toHaveCount(0);
 await page.getByRole("button", { name: "3번 구간 삭제" }).click();
 const first = page.getByRole("region", { name: "1번 구간", exact: true });
 const second = page.getByRole("region", { name: "2번 구간", exact: true });
 await first.getByLabel("시간(초)").fill("30"); await first.getByLabel("속도(km/h)").fill("3.6");
 await second.getByLabel("시간(초)").fill("30"); await second.getByLabel("속도(km/h)").fill("7.2"); await second.getByLabel("경사(%)").fill("6");
 await page.getByLabel("전체 구성 반복 횟수").fill("2");
 await page.getByLabel("구간 전환 음성·진동 알림").uncheck();
 await page.clock.install();
 await page.getByRole("button", { name: "구간 운동 시작" }).click();
 await expect(page.getByRole("heading", { name: "걷기", exact: true })).toBeVisible();
 await page.clock.fastForward(30000);
 await expect(page.getByRole("heading", { name: "달리기", exact: true })).toBeVisible();
 await expect(page.getByText("6%", { exact: true })).toBeVisible();
 await page.getByRole("button", { name: "일시정지", exact: true }).click();
 const time = await page.getByLabel("현재 구간 남은 시간").textContent();
 await page.clock.fastForward(30000);
 await expect(page.getByLabel("현재 구간 남은 시간")).toHaveText(time!);
 await page.screenshot({ path: info.outputPath("interval-paused.png"), fullPage: true });
 await page.reload({ waitUntil: "networkidle" });
 await page.getByRole("button", { name: "이어하기", exact: true }).click();
 await expect(page.getByRole("status")).toHaveText("일시정지");
 await page.getByRole("button", { name: "계속하기", exact: true }).click();
 await page.clock.fastForward(90000);
 await expect(page.getByRole("status")).toHaveText("구간 운동 종료");
 await page.getByRole("button", { name: "런닝 기록 저장", exact: true }).click();
 await expect(page.getByRole("status")).toHaveText("런닝 기록에 저장했어요");
 const rows = await dbQuery<{ duration_sec: number; distance_m: number; incline: number }>("select duration_sec,distance_m,incline from run_sessions where user_id=(select id from auth.users where email=$1)",[email]);
 expect(rows).toHaveLength(1); expect(rows[0].duration_sec).toBe(120); expect(rows[0].distance_m).toBe(180); expect(Number(rows[0].incline)).toBe(3);
 await page.getByRole("link", { name: "런닝 기록 보기" }).click();
 await expect(page).toHaveURL(/running-records/);
});
