import {mkdirSync,readFileSync,writeFileSync,copyFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import sharp from 'sharp';
const project=resolve('.');
const out=resolve('tools/media/imports/exercise-video-20260925/wrist-curl-16');
const id='behind-the-back-wrist-curl';
const generation=JSON.parse(readFileSync(join(out,'generation.json'),'utf8'));
const guides=join(out,'tools/media/motion-guides');
mkdirSync(guides,{recursive:true});mkdirSync(join(out,'tools/media/ai-guides'),{recursive:true});mkdirSync(join(out,'public/exercise-guides/ai-v3'),{recursive:true});
copyFileSync(generation.path,join(out,'sheet.png'));
const catalog=JSON.parse(readFileSync('tools/media/ai-guides/catalog.json','utf8'));
writeFileSync(join(out,'tools/media/ai-guides/catalog.json'),JSON.stringify(catalog.filter(x=>x.id===id)));
await sharp(join(out,'sheet.png')).removeAlpha().jpeg({quality:96}).toFile(join(guides,id+'.jpg'));
writeFileSync(join(guides,id+'.json'),JSON.stringify({id,prompt:generation.prompt+'\n\n'+generation.editPrompt,equipment:'barbell',sources:generation.sources,panels:16,cycle:'reverse',cutout:true}));
process.chdir(out);
const {manageMotionGuides}=await import(pathToFileURL(join(project,'tools/media/manage-motion-guides.mjs')));
await manageMotionGuides('motion-build',id);
