/**
 * 세계 음식 카탈로그 — 중식·일식·양식·기타 아시아·그외. food-catalog.ts 에 병합된다.
 * 정적 카탈로그(한식 위주)에 없는 메뉴를 대량 보강. 병합 시 이름(정규화) 중복은 자동 제거.
 * 값은 1회 제공량 근사치(관용값). 정밀 영양분석용 아님.
 */

import type { FoodItem } from "@/features/diet/food-catalog-types";

export const WORLD_FOOD_ITEMS: FoodItem[] = [
  // ── 중식
  { id: "w-yangjangpi", name: "양장피", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 420, protein: 22, carbs: 38, fat: 20 },
  { id: "w-yusanseul", name: "유산슬", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 480, protein: 30, carbs: 24, fat: 28 },
  { id: "w-kkanpunggi", name: "깐풍기", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 620, protein: 34, carbs: 40, fat: 34 },
  { id: "w-lajogi", name: "라조기", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 590, protein: 33, carbs: 38, fat: 32 },
  { id: "w-yuringi", name: "유린기", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 560, protein: 35, carbs: 34, fat: 30 },
  { id: "w-palbochae", name: "팔보채", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 440, protein: 32, carbs: 26, fat: 22 },
  { id: "w-mapadubu", name: "마파두부", category: "고기·계란", cuisine: "중식", amount: "1인분", kcal: 380, protein: 22, carbs: 20, fat: 24 },
  { id: "w-eohyanggaji", name: "어향가지", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 340, protein: 8, carbs: 30, fat: 22 },
  { id: "w-dongpayuk", name: "동파육", category: "고기·계란", cuisine: "중식", amount: "1인분", kcal: 680, protein: 26, carbs: 18, fat: 56 },
  { id: "w-huoguo", name: "훠궈", category: "국·찌개", cuisine: "중식", amount: "1인분", kcal: 620, protein: 40, carbs: 30, fat: 38 },
  { id: "w-malaxiangguo", name: "마라샹궈", category: "고기·계란", cuisine: "중식", amount: "1인분", kcal: 720, protein: 34, carbs: 42, fat: 44 },
  { id: "w-guobarou", name: "꿔바로우", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 650, protein: 28, carbs: 58, fat: 34 },
  { id: "w-tantanmyeon", name: "탄탄면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 620, protein: 24, carbs: 68, fat: 28 },
  { id: "w-wuroumyeon", name: "우육면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 560, protein: 30, carbs: 66, fat: 18 },
  { id: "w-hagau", name: "하가우", category: "밥·면", cuisine: "중식", amount: "4개", kcal: 220, protein: 12, carbs: 26, fat: 8 },
  { id: "w-xiaolongbao", name: "샤오롱바오", category: "밥·면", cuisine: "중식", amount: "4개", kcal: 280, protein: 14, carbs: 30, fat: 12 },
  { id: "w-chashaobao", name: "차슈바오", category: "빵·간식", cuisine: "중식", amount: "1개", kcal: 240, protein: 9, carbs: 34, fat: 8 },
  { id: "w-shaomai", name: "샤오마이", category: "밥·면", cuisine: "중식", amount: "4개", kcal: 250, protein: 13, carbs: 24, fat: 11 },
  { id: "w-changfen", name: "창펀", category: "밥·면", cuisine: "중식", amount: "1접시", kcal: 260, protein: 10, carbs: 40, fat: 6 },
  { id: "w-eggtart-chinese", name: "에그타르트(홍콩)", category: "빵·간식", cuisine: "중식", amount: "1개", kcal: 200, protein: 4, carbs: 22, fat: 11 },
  { id: "w-yangzhou-bokkeumbap", name: "양저우 볶음밥", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 560, protein: 18, carbs: 78, fat: 18 },
  { id: "w-shrimp-friedrice", name: "새우볶음밥", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 540, protein: 20, carbs: 76, fat: 16 },
  { id: "w-xo-friedrice", name: "XO 볶음밥", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 590, protein: 19, carbs: 74, fat: 22 },
  { id: "w-malatang", name: "마라탕(중식)", category: "국·찌개", cuisine: "중식", amount: "1그릇", kcal: 520, protein: 26, carbs: 44, fat: 26 },
  { id: "w-malalongxia", name: "마라롱샤", category: "생선·해산물", cuisine: "중식", amount: "1인분", kcal: 480, protein: 34, carbs: 20, fat: 28 },
  { id: "w-beijing-kaoya", name: "북경오리", category: "고기·계란", cuisine: "중식", amount: "4쪽", kcal: 460, protein: 26, carbs: 22, fat: 30 },
  { id: "w-ganshao-saeu", name: "깐쇼새우", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 480, protein: 26, carbs: 40, fat: 22 },
  { id: "w-chili-saeu", name: "칠리새우", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 460, protein: 27, carbs: 38, fat: 20 },
  { id: "w-gochujapchae", name: "고추잡채", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 380, protein: 22, carbs: 24, fat: 20 },
  { id: "w-yangkkochi", name: "양꼬치(중식)", category: "고기·계란", cuisine: "중식", amount: "4꼬치", kcal: 380, protein: 28, carbs: 6, fat: 26 },
  { id: "w-huntun", name: "훈툰", category: "국·찌개", cuisine: "중식", amount: "1그릇", kcal: 300, protein: 16, carbs: 34, fat: 10 },
  { id: "w-wantanmyeon", name: "완탕면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 420, protein: 20, carbs: 58, fat: 12 },
  { id: "w-zhacai", name: "짜사이", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 60, protein: 2, carbs: 8, fat: 2 },
  { id: "w-jjajangmyeon-c", name: "작장면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 640, protein: 18, carbs: 92, fat: 20 },
  { id: "w-liangpi", name: "량피", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 380, protein: 8, carbs: 62, fat: 10 },
  { id: "w-dandan-rice", name: "루러우판", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 560, protein: 22, carbs: 70, fat: 22 },
  { id: "w-gongbao-jiding", name: "궁보계정", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 520, protein: 30, carbs: 28, fat: 30 },
  { id: "w-tangcuroyu", name: "탕수육(중식)", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 680, protein: 28, carbs: 64, fat: 34 },
  { id: "w-chow-mein", name: "차우멘", category: "밥·면", cuisine: "중식", amount: "1접시", kcal: 520, protein: 18, carbs: 66, fat: 20 },
  { id: "w-lo-mein", name: "로우멘", category: "밥·면", cuisine: "중식", amount: "1접시", kcal: 540, protein: 17, carbs: 70, fat: 20 },
  { id: "w-dongpo-tofu", name: "홍쇼두부", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 320, protein: 18, carbs: 20, fat: 20 },
  { id: "w-suanla-tang", name: "쏸라탕", category: "국·찌개", cuisine: "중식", amount: "1그릇", kcal: 220, protein: 12, carbs: 20, fat: 10 },
  { id: "w-mala-tofu-skin", name: "마라 푸주", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 280, protein: 18, carbs: 14, fat: 18 },
  { id: "w-baozi-pork", name: "돼지고기 바오즈", category: "빵·간식", cuisine: "중식", amount: "1개", kcal: 250, protein: 11, carbs: 34, fat: 8 },
  { id: "w-shengjianbao", name: "성젠바오", category: "밥·면", cuisine: "중식", amount: "4개", kcal: 340, protein: 15, carbs: 36, fat: 15 },
  { id: "w-guotie", name: "궈톄", category: "밥·면", cuisine: "중식", amount: "5개", kcal: 360, protein: 15, carbs: 34, fat: 18 },
  { id: "w-mala-duck-blood", name: "마라 오리선지", category: "국·찌개", cuisine: "중식", amount: "1인분", kcal: 300, protein: 22, carbs: 12, fat: 18 },
  { id: "w-tianjin-fanqie", name: "토마토 계란볶음", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 240, protein: 12, carbs: 14, fat: 15 },
  { id: "w-ganbian-doujiao", name: "간볜 콩볶음", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 260, protein: 8, carbs: 20, fat: 18 },
  { id: "w-yuxiang-rousi", name: "위샹로우쓰", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 420, protein: 24, carbs: 26, fat: 24 },
  { id: "w-suan-rong-choy", name: "청경채 마늘볶음", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 120, protein: 4, carbs: 10, fat: 8 },
  { id: "w-chunjuan", name: "춘권", category: "빵·간식", cuisine: "중식", amount: "3개", kcal: 300, protein: 8, carbs: 32, fat: 16 },
  { id: "w-mala-lotus", name: "마라 연근", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 180, protein: 4, carbs: 28, fat: 6 },
  { id: "w-crispy-beef", name: "크리스피 소고기", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 560, protein: 26, carbs: 44, fat: 30 },
  { id: "w-orange-chicken", name: "오렌지 치킨", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 600, protein: 26, carbs: 56, fat: 30 },
  { id: "w-sweet-sour-pork-hk", name: "구루러우", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 640, protein: 26, carbs: 58, fat: 32 },
  { id: "w-salt-pepper-squid", name: "소금후추 오징어", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 420, protein: 24, carbs: 26, fat: 24 },
  { id: "w-steamed-fish-ch", name: "칭정위(찐생선)", category: "생선·해산물", cuisine: "중식", amount: "1인분", kcal: 320, protein: 34, carbs: 6, fat: 18 },
  { id: "w-braised-eggplant-ch", name: "홍쇼 가지", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 300, protein: 6, carbs: 28, fat: 18 },
  { id: "w-scallion-pancake", name: "총유빙(파전병)", category: "빵·간식", cuisine: "중식", amount: "1장", kcal: 360, protein: 8, carbs: 44, fat: 18 },
  { id: "w-chinese-broccoli-oyster", name: "가이란 굴소스", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 140, protein: 5, carbs: 12, fat: 8 },
  { id: "w-mala-quail-egg", name: "마라 메추리알", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 260, protein: 16, carbs: 8, fat: 18 },
  { id: "w-beijing-zhajiang", name: "베이징 짜장면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 600, protein: 20, carbs: 82, fat: 20 },
  { id: "w-crab-xiaolongbao", name: "게살 샤오롱바오", category: "밥·면", cuisine: "중식", amount: "4개", kcal: 300, protein: 15, carbs: 30, fat: 13 },
  { id: "w-lotus-paste-bun", name: "연꽃빵(롄룽바오)", category: "빵·간식", cuisine: "중식", amount: "1개", kcal: 210, protein: 5, carbs: 36, fat: 6 },
  { id: "w-mango-pudding-ch", name: "망고푸딩(홍콩)", category: "빵·간식", cuisine: "중식", amount: "1개", kcal: 190, protein: 3, carbs: 30, fat: 7 },
  { id: "w-almond-tofu", name: "행인두부", category: "빵·간식", cuisine: "중식", amount: "1접시", kcal: 160, protein: 3, carbs: 24, fat: 6 },
  { id: "w-tangyuan", name: "탕위안", category: "빵·간식", cuisine: "중식", amount: "1그릇", kcal: 280, protein: 5, carbs: 52, fat: 6 },
  { id: "w-douhua", name: "더우화", category: "빵·간식", cuisine: "중식", amount: "1그릇", kcal: 180, protein: 7, carbs: 28, fat: 4 },
  { id: "w-hong-kong-milk-tea", name: "홍콩식 밀크티", category: "음료", cuisine: "중식", amount: "1잔", kcal: 160, protein: 4, carbs: 22, fat: 6 },
  { id: "w-chrysanthemum-tea", name: "국화차", category: "음료", cuisine: "중식", amount: "1잔", kcal: 40, protein: 0, carbs: 10, fat: 0 },
  { id: "w-cong-you-ban-mian", name: "총유반면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 480, protein: 12, carbs: 68, fat: 18 },
  { id: "w-biang-biang-mian", name: "비앙비앙면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 620, protein: 16, carbs: 88, fat: 22 },
  { id: "w-dan-dan-noodle-dry", name: "건탄탄면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 560, protein: 20, carbs: 66, fat: 24 },
  { id: "w-sesame-noodle", name: "마장면", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 540, protein: 16, carbs: 70, fat: 22 },
  { id: "w-clay-pot-rice", name: "바오자이판", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 620, protein: 24, carbs: 82, fat: 22 },
  { id: "w-congee-century-egg", name: "피단 죽", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 260, protein: 12, carbs: 40, fat: 6 },
  { id: "w-turnip-cake", name: "무떡(로백고)", category: "빵·간식", cuisine: "중식", amount: "3조각", kcal: 240, protein: 6, carbs: 30, fat: 10 },
  { id: "w-taro-cake", name: "토란떡", category: "빵·간식", cuisine: "중식", amount: "3조각", kcal: 250, protein: 5, carbs: 32, fat: 11 },
  { id: "w-sesame-ball", name: "지마추(깨경단)", category: "빵·간식", cuisine: "중식", amount: "3개", kcal: 300, protein: 5, carbs: 44, fat: 12 },
  { id: "w-peking-pork-ribs", name: "경장육사", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 520, protein: 26, carbs: 30, fat: 30 },
  { id: "w-mapo-eggplant", name: "마파가지", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 320, protein: 8, carbs: 24, fat: 20 },
  { id: "w-fish-fragrant-eggplant", name: "위샹 가지덮밥", category: "밥·면", cuisine: "중식", amount: "1그릇", kcal: 520, protein: 12, carbs: 74, fat: 18 },
  { id: "w-cumin-lamb", name: "쯔란 양고기", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 480, protein: 30, carbs: 12, fat: 34 },
  { id: "w-kung-pao-shrimp", name: "궁보새우", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 440, protein: 28, carbs: 24, fat: 24 },
  { id: "w-honey-walnut-shrimp", name: "허니월넛새우", category: "생선·해산물", cuisine: "중식", amount: "1접시", kcal: 560, protein: 24, carbs: 40, fat: 32 },
  { id: "w-hotpot-lamb-roll", name: "훠궈 양고기말이", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 400, protein: 24, carbs: 4, fat: 32 },
  { id: "w-mala-potato-strips", name: "마라 감자채", category: "채소·반찬", cuisine: "중식", amount: "1접시", kcal: 220, protein: 4, carbs: 28, fat: 11 },
  { id: "w-drunken-chicken", name: "취계(술닭)", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 300, protein: 28, carbs: 4, fat: 18 },
  { id: "w-general-tso-chicken", name: "제너럴 쏘 치킨", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 620, protein: 26, carbs: 54, fat: 32 },
  { id: "w-beef-broccoli-ch", name: "브로콜리 소고기볶음", category: "고기·계란", cuisine: "중식", amount: "1접시", kcal: 420, protein: 28, carbs: 22, fat: 24 },
  { id: "w-hoisin-duck-pancake", name: "오리 밀전병쌈", category: "밥·면", cuisine: "중식", amount: "3개", kcal: 380, protein: 18, carbs: 34, fat: 20 },

  // ── 일식
  { id: "w-maguro-nigiri", name: "참치초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 120, protein: 12, carbs: 14, fat: 2 },
  { id: "w-salmon-nigiri", name: "연어초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 160, protein: 12, carbs: 14, fat: 6 },
  { id: "w-ebi-nigiri", name: "새우초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 110, protein: 10, carbs: 15, fat: 1 },
  { id: "w-unagi-nigiri", name: "장어초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 180, protein: 12, carbs: 16, fat: 8 },
  { id: "w-tamago-nigiri", name: "계란초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 130, protein: 6, carbs: 18, fat: 4 },
  { id: "w-hamachi-nigiri", name: "방어초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 150, protein: 12, carbs: 14, fat: 5 },
  { id: "w-engawa-nigiri", name: "광어지느러미초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 160, protein: 11, carbs: 14, fat: 7 },
  { id: "w-uni-nigiri", name: "성게알초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 140, protein: 8, carbs: 15, fat: 6 },
  { id: "w-ikura-gunkan", name: "연어알군함", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 150, protein: 10, carbs: 15, fat: 6 },
  { id: "w-otoro-nigiri", name: "오토로초밥", category: "생선·해산물", cuisine: "일식", amount: "2개", kcal: 200, protein: 12, carbs: 14, fat: 12 },
  { id: "w-california-roll", name: "캘리포니아롤", category: "밥·면", cuisine: "일식", amount: "8조각", kcal: 340, protein: 10, carbs: 48, fat: 12 },
  { id: "w-spicy-tuna-roll", name: "매운참치롤", category: "밥·면", cuisine: "일식", amount: "8조각", kcal: 360, protein: 14, carbs: 46, fat: 12 },
  { id: "w-dragon-roll", name: "드래곤롤", category: "밥·면", cuisine: "일식", amount: "8조각", kcal: 420, protein: 14, carbs: 50, fat: 16 },
  { id: "w-maguro-sashimi", name: "참치사시미", category: "생선·해산물", cuisine: "일식", amount: "1접시", kcal: 180, protein: 34, carbs: 0, fat: 5 },
  { id: "w-salmon-sashimi", name: "연어사시미", category: "생선·해산물", cuisine: "일식", amount: "1접시", kcal: 240, protein: 28, carbs: 0, fat: 14 },
  { id: "w-hamachi-sashimi", name: "방어사시미", category: "생선·해산물", cuisine: "일식", amount: "1접시", kcal: 220, protein: 26, carbs: 0, fat: 13 },
  { id: "w-tai-sashimi", name: "도미사시미", category: "생선·해산물", cuisine: "일식", amount: "1접시", kcal: 160, protein: 30, carbs: 0, fat: 4 },
  { id: "w-tako-sashimi", name: "문어사시미", category: "생선·해산물", cuisine: "일식", amount: "1접시", kcal: 120, protein: 24, carbs: 4, fat: 2 },
  { id: "w-katsudon", name: "가츠동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 780, protein: 30, carbs: 90, fat: 32 },
  { id: "w-gyudon", name: "규동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 680, protein: 24, carbs: 92, fat: 24 },
  { id: "w-tendon", name: "텐동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 720, protein: 22, carbs: 96, fat: 28 },
  { id: "w-oyakodon", name: "오야코동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 620, protein: 28, carbs: 84, fat: 18 },
  { id: "w-butadon", name: "부타동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 700, protein: 26, carbs: 88, fat: 26 },
  { id: "w-unadon", name: "우나기동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 720, protein: 30, carbs: 90, fat: 26 },
  { id: "w-kaisendon", name: "카이센동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 520, protein: 30, carbs: 68, fat: 12 },
  { id: "w-negitoro-don", name: "네기토로동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 560, protein: 26, carbs: 68, fat: 18 },
  { id: "w-tonkotsu-ramen", name: "돈코츠라멘", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 620, protein: 28, carbs: 66, fat: 26 },
  { id: "w-miso-ramen", name: "미소라멘", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 560, protein: 24, carbs: 68, fat: 20 },
  { id: "w-shoyu-ramen", name: "쇼유라멘", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 520, protein: 24, carbs: 66, fat: 16 },
  { id: "w-shio-ramen", name: "시오라멘", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 500, protein: 22, carbs: 64, fat: 15 },
  { id: "w-tsukemen", name: "츠케멘", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 680, protein: 28, carbs: 84, fat: 22 },
  { id: "w-tantanmen-jp", name: "탄탄멘(일본)", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 640, protein: 24, carbs: 66, fat: 30 },
  { id: "w-kake-udon", name: "카케우동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 380, protein: 12, carbs: 72, fat: 4 },
  { id: "w-tempura-udon", name: "튀김우동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 560, protein: 18, carbs: 78, fat: 18 },
  { id: "w-curry-udon", name: "카레우동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 600, protein: 18, carbs: 82, fat: 20 },
  { id: "w-yaki-udon", name: "야키우동", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 540, protein: 16, carbs: 74, fat: 18 },
  { id: "w-zaru-soba", name: "자루소바", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 340, protein: 14, carbs: 66, fat: 3 },
  { id: "w-tempura-soba", name: "튀김소바", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 520, protein: 18, carbs: 72, fat: 16 },
  { id: "w-gyukatsu", name: "규카츠", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 620, protein: 34, carbs: 32, fat: 38 },
  { id: "w-tonkatsu-jp", name: "돈카츠(일식)", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 660, protein: 30, carbs: 40, fat: 38 },
  { id: "w-menchi-katsu", name: "멘치카츠", category: "고기·계란", cuisine: "일식", amount: "2개", kcal: 480, protein: 22, carbs: 28, fat: 30 },
  { id: "w-ebi-fry", name: "새우튀김(에비후라이)", category: "생선·해산물", cuisine: "일식", amount: "3개", kcal: 380, protein: 18, carbs: 30, fat: 20 },
  { id: "w-karaage", name: "가라아게", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 480, protein: 28, carbs: 24, fat: 28 },
  { id: "w-yakitori-momo", name: "야키토리(닭허벅지)", category: "고기·계란", cuisine: "일식", amount: "3꼬치", kcal: 300, protein: 26, carbs: 6, fat: 18 },
  { id: "w-tsukune", name: "츠쿠네", category: "고기·계란", cuisine: "일식", amount: "3꼬치", kcal: 320, protein: 22, carbs: 12, fat: 20 },
  { id: "w-negima", name: "네기마", category: "고기·계란", cuisine: "일식", amount: "3꼬치", kcal: 260, protein: 24, carbs: 6, fat: 15 },
  { id: "w-okonomiyaki", name: "오코노미야키", category: "빵·간식", cuisine: "일식", amount: "1장", kcal: 560, protein: 20, carbs: 56, fat: 28 },
  { id: "w-takoyaki", name: "타코야키", category: "빵·간식", cuisine: "일식", amount: "6개", kcal: 420, protein: 14, carbs: 44, fat: 20 },
  { id: "w-monjayaki", name: "몬자야키", category: "빵·간식", cuisine: "일식", amount: "1인분", kcal: 400, protein: 14, carbs: 42, fat: 18 },
  { id: "w-yosenabe", name: "요세나베", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 420, protein: 34, carbs: 24, fat: 18 },
  { id: "w-shabu-shabu-jp", name: "샤브샤브(일식)", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 480, protein: 36, carbs: 20, fat: 26 },
  { id: "w-sukiyaki", name: "스키야키", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 620, protein: 34, carbs: 30, fat: 36 },
  { id: "w-motsunabe", name: "모츠나베", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 520, protein: 28, carbs: 22, fat: 32 },
  { id: "w-chanko-nabe", name: "창코나베", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 540, protein: 38, carbs: 26, fat: 28 },
  { id: "w-tempura-moriawase", name: "모듬튀김(텐푸라)", category: "생선·해산물", cuisine: "일식", amount: "1인분", kcal: 520, protein: 18, carbs: 42, fat: 30 },
  { id: "w-kakiage", name: "카키아게", category: "채소·반찬", cuisine: "일식", amount: "2개", kcal: 360, protein: 8, carbs: 34, fat: 22 },
  { id: "w-gyutan", name: "규탕(소혀구이)", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 420, protein: 26, carbs: 4, fat: 34 },
  { id: "w-oden", name: "오뎅(일본식)", category: "국·찌개", cuisine: "일식", amount: "1인분", kcal: 280, protein: 18, carbs: 26, fat: 10 },
  { id: "w-natto", name: "낫토", category: "고기·계란", cuisine: "일식", amount: "1팩", kcal: 200, protein: 17, carbs: 12, fat: 11 },
  { id: "w-chawanmushi", name: "자완무시", category: "고기·계란", cuisine: "일식", amount: "1개", kcal: 120, protein: 10, carbs: 6, fat: 6 },
  { id: "w-agedashi-tofu", name: "아게다시도후", category: "채소·반찬", cuisine: "일식", amount: "1인분", kcal: 260, protein: 12, carbs: 18, fat: 16 },
  { id: "w-edamame", name: "에다마메", category: "채소·반찬", cuisine: "일식", amount: "1접시", kcal: 150, protein: 12, carbs: 12, fat: 6 },
  { id: "w-hiyayakko", name: "히야얏코", category: "채소·반찬", cuisine: "일식", amount: "1접시", kcal: 120, protein: 10, carbs: 6, fat: 7 },
  { id: "w-onigiri-tuna", name: "참치마요 주먹밥", category: "밥·면", cuisine: "일식", amount: "1개", kcal: 220, protein: 8, carbs: 34, fat: 6 },
  { id: "w-onigiri-salmon", name: "연어 주먹밥", category: "밥·면", cuisine: "일식", amount: "1개", kcal: 210, protein: 9, carbs: 34, fat: 5 },
  { id: "w-omurice-jp", name: "오므라이스(일식)", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 620, protein: 20, carbs: 78, fat: 24 },
  { id: "w-katsu-curry-jp", name: "가츠카레(일식)", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 820, protein: 30, carbs: 96, fat: 34 },
  { id: "w-japanese-curry-rice", name: "일본식 카레라이스", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 640, protein: 18, carbs: 92, fat: 22 },
  { id: "w-hayashi-rice", name: "하야시라이스", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 620, protein: 20, carbs: 82, fat: 22 },
  { id: "w-chahan-jp", name: "챠항(일식볶음밥)", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 560, protein: 16, carbs: 76, fat: 20 },
  { id: "w-yakisoba-jp", name: "야키소바(일식)", category: "밥·면", cuisine: "일식", amount: "1접시", kcal: 540, protein: 16, carbs: 72, fat: 20 },
  { id: "w-hiyashi-chuka", name: "히야시츄카", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 480, protein: 20, carbs: 66, fat: 14 },
  { id: "w-tonjiru", name: "돈지루", category: "국·찌개", cuisine: "일식", amount: "1그릇", kcal: 220, protein: 12, carbs: 20, fat: 10 },
  { id: "w-gyoza-jp", name: "교자(일식만두)", category: "밥·면", cuisine: "일식", amount: "5개", kcal: 340, protein: 14, carbs: 34, fat: 16 },
  { id: "w-mentaiko-pasta-jp", name: "명란파스타(일식)", category: "밥·면", cuisine: "일식", amount: "1접시", kcal: 620, protein: 22, carbs: 72, fat: 26 },
  { id: "w-mochi", name: "모찌(찹쌀떡)", category: "빵·간식", cuisine: "일식", amount: "2개", kcal: 220, protein: 3, carbs: 48, fat: 2 },
  { id: "w-dorayaki", name: "도라야키", category: "빵·간식", cuisine: "일식", amount: "1개", kcal: 240, protein: 6, carbs: 44, fat: 5 },
  { id: "w-taiyaki", name: "타이야키", category: "빵·간식", cuisine: "일식", amount: "1개", kcal: 230, protein: 5, carbs: 42, fat: 5 },
  { id: "w-matcha-ice", name: "말차 아이스크림", category: "빵·간식", cuisine: "일식", amount: "1개", kcal: 210, protein: 4, carbs: 26, fat: 10 },
  { id: "w-daifuku", name: "다이후쿠", category: "빵·간식", cuisine: "일식", amount: "1개", kcal: 190, protein: 3, carbs: 40, fat: 2 },
  { id: "w-castella-jp", name: "카스테라", category: "빵·간식", cuisine: "일식", amount: "1조각", kcal: 180, protein: 4, carbs: 30, fat: 5 },
  { id: "w-melonpan", name: "멜론빵", category: "빵·간식", cuisine: "일식", amount: "1개", kcal: 320, protein: 6, carbs: 50, fat: 11 },
  { id: "w-matcha-latte", name: "말차라떼", category: "음료", cuisine: "일식", amount: "1잔", kcal: 180, protein: 6, carbs: 26, fat: 6 },
  { id: "w-ramune", name: "라무네", category: "음료", cuisine: "일식", amount: "1병", kcal: 90, protein: 0, carbs: 23, fat: 0 },
  { id: "w-sake", name: "사케", category: "음료", cuisine: "일식", amount: "1잔", kcal: 130, protein: 0, carbs: 5, fat: 0 },
  { id: "w-genmaicha", name: "겐마이차", category: "음료", cuisine: "일식", amount: "1잔", kcal: 5, protein: 0, carbs: 1, fat: 0 },
  { id: "w-saba-shioyaki", name: "고등어소금구이(사바)", category: "생선·해산물", cuisine: "일식", amount: "1인분", kcal: 320, protein: 28, carbs: 2, fat: 22 },
  { id: "w-teriyaki-chicken-jp", name: "데리야키 치킨", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 480, protein: 34, carbs: 26, fat: 24 },
  { id: "w-buta-kakuni", name: "부타 카쿠니", category: "고기·계란", cuisine: "일식", amount: "1인분", kcal: 560, protein: 26, carbs: 14, fat: 44 },
  { id: "w-ochazuke", name: "오차즈케", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 260, protein: 10, carbs: 46, fat: 4 },
  { id: "w-inari-sushi-jp", name: "유부초밥(이나리)", category: "밥·면", cuisine: "일식", amount: "3개", kcal: 300, protein: 8, carbs: 52, fat: 7 },
  { id: "w-chirashi-sushi", name: "치라시스시", category: "밥·면", cuisine: "일식", amount: "1그릇", kcal: 520, protein: 24, carbs: 72, fat: 12 },
  { id: "w-korokke-jp", name: "고로케(일식)", category: "채소·반찬", cuisine: "일식", amount: "2개", kcal: 360, protein: 8, carbs: 42, fat: 18 },

  // ── 양식
  { id: "w-carbonara", name: "까르보나라", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 720, protein: 26, carbs: 78, fat: 34 },
  { id: "w-aglio-olio", name: "알리오올리오", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 560, protein: 14, carbs: 78, fat: 22 },
  { id: "w-vongole", name: "봉골레파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 540, protein: 22, carbs: 72, fat: 18 },
  { id: "w-abalone-guts-pasta", name: "전복내장파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 640, protein: 24, carbs: 74, fat: 28 },
  { id: "w-arrabiata", name: "아라비아타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 540, protein: 15, carbs: 82, fat: 16 },
  { id: "w-ragu-pasta", name: "라구파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 680, protein: 28, carbs: 76, fat: 28 },
  { id: "w-pesto-pasta", name: "페스토파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 640, protein: 18, carbs: 74, fat: 30 },
  { id: "w-truffle-pasta", name: "트러플파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 700, protein: 20, carbs: 76, fat: 34 },
  { id: "w-tomato-pasta", name: "토마토파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 520, protein: 16, carbs: 82, fat: 14 },
  { id: "w-cream-pasta", name: "크림파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 700, protein: 20, carbs: 76, fat: 34 },
  { id: "w-rose-pasta", name: "로제파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 660, protein: 20, carbs: 78, fat: 30 },
  { id: "w-bolognese", name: "볼로네제", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 660, protein: 27, carbs: 78, fat: 26 },
  { id: "w-shrimp-rose-pasta", name: "새우로제파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 680, protein: 26, carbs: 76, fat: 30 },
  { id: "w-seafood-tomato-pasta", name: "해산물토마토파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 620, protein: 28, carbs: 74, fat: 22 },
  { id: "w-lasagna-w", name: "라자냐", category: "밥·면", cuisine: "양식", amount: "1인분", kcal: 680, protein: 30, carbs: 58, fat: 36 },
  { id: "w-gnocchi", name: "뇨끼", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 560, protein: 16, carbs: 78, fat: 20 },
  { id: "w-mac-and-cheese", name: "맥앤치즈", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 620, protein: 22, carbs: 62, fat: 32 },
  { id: "w-mushroom-risotto", name: "버섯리조또", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 560, protein: 14, carbs: 74, fat: 22 },
  { id: "w-seafood-risotto", name: "해산물리조또", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 580, protein: 24, carbs: 72, fat: 20 },
  { id: "w-truffle-risotto", name: "트러플리조또", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 620, protein: 16, carbs: 74, fat: 28 },
  { id: "w-margherita-pizza", name: "마르게리타피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 500, protein: 20, carbs: 58, fat: 20 },
  { id: "w-pepperoni-pizza", name: "페퍼로니피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 580, protein: 24, carbs: 56, fat: 28 },
  { id: "w-gorgonzola-pizza", name: "고르곤졸라피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 560, protein: 22, carbs: 56, fat: 26 },
  { id: "w-hawaiian-pizza", name: "하와이안피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 540, protein: 22, carbs: 60, fat: 22 },
  { id: "w-bulgogi-pizza", name: "불고기피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 580, protein: 24, carbs: 60, fat: 26 },
  { id: "w-quattro-formaggi", name: "콰트로포르마지", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 600, protein: 26, carbs: 54, fat: 30 },
  { id: "w-truffle-pizza", name: "트러플피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 590, protein: 22, carbs: 56, fat: 30 },
  { id: "w-diavola-pizza", name: "디아볼라피자", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 600, protein: 24, carbs: 56, fat: 30 },
  { id: "w-ribeye-steak", name: "립아이스테이크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 720, protein: 48, carbs: 4, fat: 58 },
  { id: "w-sirloin-steak", name: "등심스테이크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 560, protein: 46, carbs: 4, fat: 40 },
  { id: "w-tenderloin-steak", name: "안심스테이크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 520, protein: 48, carbs: 4, fat: 34 },
  { id: "w-tbone-steak", name: "티본스테이크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 780, protein: 52, carbs: 4, fat: 62 },
  { id: "w-tomahawk-steak", name: "토마호크스테이크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 900, protein: 58, carbs: 4, fat: 74 },
  { id: "w-gambas", name: "감바스", category: "생선·해산물", cuisine: "양식", amount: "1접시", kcal: 420, protein: 26, carbs: 10, fat: 30 },
  { id: "w-minestrone", name: "미네스트로네", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 220, protein: 8, carbs: 32, fat: 7 },
  { id: "w-clam-chowder", name: "클램차우더", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 340, protein: 14, carbs: 28, fat: 20 },
  { id: "w-bouillabaisse", name: "부야베스", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 380, protein: 30, carbs: 18, fat: 20 },
  { id: "w-goulash", name: "굴라쉬", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 420, protein: 28, carbs: 26, fat: 22 },
  { id: "w-pumpkin-soup", name: "단호박수프", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 220, protein: 5, carbs: 30, fat: 10 },
  { id: "w-mushroom-soup", name: "양송이수프", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 240, protein: 6, carbs: 22, fat: 14 },
  { id: "w-onion-soup", name: "어니언수프", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 280, protein: 10, carbs: 26, fat: 14 },
  { id: "w-tomato-soup", name: "토마토수프", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 200, protein: 5, carbs: 28, fat: 8 },
  { id: "w-beef-stew-w", name: "비프스튜", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 460, protein: 30, carbs: 30, fat: 24 },
  { id: "w-ratatouille", name: "라따뚜이", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 220, protein: 5, carbs: 26, fat: 12 },
  { id: "w-caesar-salad", name: "시저샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 360, protein: 12, carbs: 16, fat: 28 },
  { id: "w-cobb-salad", name: "콥샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 420, protein: 26, carbs: 12, fat: 30 },
  { id: "w-caprese-salad", name: "카프레제샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 320, protein: 16, carbs: 10, fat: 24 },
  { id: "w-greek-salad", name: "그릭샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 280, protein: 9, carbs: 14, fat: 22 },
  { id: "w-burrata-salad", name: "부라타샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 400, protein: 18, carbs: 12, fat: 32 },
  { id: "w-nicoise-salad", name: "니수아즈샐러드", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 380, protein: 24, carbs: 18, fat: 24 },
  { id: "w-eggs-benedict", name: "에그베네딕트", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 520, protein: 24, carbs: 30, fat: 34 },
  { id: "w-pancake-w", name: "팬케이크", category: "빵·간식", cuisine: "양식", amount: "3장", kcal: 520, protein: 12, carbs: 74, fat: 18 },
  { id: "w-french-toast", name: "프렌치토스트", category: "빵·간식", cuisine: "양식", amount: "2장", kcal: 480, protein: 14, carbs: 58, fat: 20 },
  { id: "w-omelette", name: "오믈렛", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 380, protein: 22, carbs: 6, fat: 30 },
  { id: "w-waffle-w", name: "와플(양식)", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 400, protein: 8, carbs: 52, fat: 18 },
  { id: "w-avocado-toast", name: "아보카도토스트", category: "빵·간식", cuisine: "양식", amount: "1인분", kcal: 380, protein: 12, carbs: 36, fat: 22 },
  { id: "w-granola-bowl", name: "그래놀라볼", category: "빵·간식", cuisine: "양식", amount: "1그릇", kcal: 420, protein: 12, carbs: 62, fat: 14 },
  { id: "w-cheeseburger", name: "치즈버거", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 620, protein: 30, carbs: 44, fat: 36 },
  { id: "w-bacon-burger", name: "베이컨버거", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 720, protein: 34, carbs: 44, fat: 44 },
  { id: "w-double-burger", name: "더블패티버거", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 860, protein: 46, carbs: 44, fat: 54 },
  { id: "w-mushroom-burger", name: "머쉬룸버거", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 640, protein: 30, carbs: 46, fat: 36 },
  { id: "w-blt-sandwich", name: "BLT샌드위치", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 480, protein: 18, carbs: 42, fat: 26 },
  { id: "w-club-sandwich", name: "클럽샌드위치", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 560, protein: 28, carbs: 46, fat: 28 },
  { id: "w-panini", name: "파니니", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 520, protein: 24, carbs: 48, fat: 26 },
  { id: "w-croque-monsieur", name: "크로크무슈", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 540, protein: 26, carbs: 40, fat: 30 },
  { id: "w-reuben-sandwich", name: "루벤샌드위치", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 600, protein: 30, carbs: 44, fat: 32 },
  { id: "w-philly-cheesesteak", name: "필리치즈스테이크", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 680, protein: 34, carbs: 50, fat: 36 },
  { id: "w-hotdog-w", name: "핫도그(양식)", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 400, protein: 14, carbs: 34, fat: 24 },
  { id: "w-french-fries", name: "감자튀김", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 380, protein: 5, carbs: 48, fat: 19 },
  { id: "w-mashed-potato", name: "매쉬포테이토", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 280, protein: 5, carbs: 36, fat: 13 },
  { id: "w-potato-gratin", name: "감자그라탕", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 420, protein: 10, carbs: 38, fat: 26 },
  { id: "w-hash-brown", name: "해쉬브라운", category: "채소·반찬", cuisine: "양식", amount: "2개", kcal: 300, protein: 4, carbs: 32, fat: 18 },
  { id: "w-wedge-potato", name: "웨지감자", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 340, protein: 5, carbs: 42, fat: 17 },
  { id: "w-onion-rings", name: "어니언링", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 400, protein: 6, carbs: 46, fat: 22 },
  { id: "w-macaroni-gratin", name: "마카로니그라탕", category: "밥·면", cuisine: "양식", amount: "1인분", kcal: 540, protein: 20, carbs: 52, fat: 28 },
  { id: "w-seafood-gratin", name: "해산물그라탕", category: "생선·해산물", cuisine: "양식", amount: "1인분", kcal: 500, protein: 24, carbs: 30, fat: 30 },
  { id: "w-fish-and-chips-w", name: "피시앤칩스", category: "생선·해산물", cuisine: "양식", amount: "1인분", kcal: 780, protein: 30, carbs: 68, fat: 42 },
  { id: "w-grilled-salmon", name: "연어스테이크", category: "생선·해산물", cuisine: "양식", amount: "1인분", kcal: 420, protein: 36, carbs: 4, fat: 28 },
  { id: "w-lobster-thermidor", name: "랍스터테르미도르", category: "생선·해산물", cuisine: "양식", amount: "1인분", kcal: 560, protein: 34, carbs: 12, fat: 40 },
  { id: "w-grilled-octopus", name: "문어그릴", category: "생선·해산물", cuisine: "양식", amount: "1접시", kcal: 320, protein: 28, carbs: 12, fat: 18 },
  { id: "w-mussels-white-wine", name: "홍합화이트와인찜", category: "생선·해산물", cuisine: "양식", amount: "1인분", kcal: 360, protein: 28, carbs: 16, fat: 18 },
  { id: "w-oysters-raw", name: "생굴(하프셸)", category: "생선·해산물", cuisine: "양식", amount: "6개", kcal: 100, protein: 10, carbs: 6, fat: 3 },
  { id: "w-tapas-patatas-bravas", name: "파타타스브라바스", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 340, protein: 6, carbs: 40, fat: 18 },
  { id: "w-spanish-omelette", name: "스페인식오믈렛", category: "고기·계란", cuisine: "양식", amount: "1조각", kcal: 320, protein: 14, carbs: 22, fat: 20 },
  { id: "w-jamon", name: "하몽", category: "고기·계란", cuisine: "양식", amount: "1접시", kcal: 240, protein: 22, carbs: 1, fat: 16 },
  { id: "w-croquette-spanish", name: "크로켓(스페인)", category: "채소·반찬", cuisine: "양식", amount: "3개", kcal: 340, protein: 10, carbs: 30, fat: 20 },
  { id: "w-chicken-parmesan", name: "치킨파르미지아나", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 640, protein: 40, carbs: 40, fat: 34 },
  { id: "w-chicken-cordon-bleu", name: "치킨코르동블루", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 620, protein: 38, carbs: 30, fat: 36 },
  { id: "w-roast-chicken", name: "로스트치킨", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 480, protein: 42, carbs: 4, fat: 32 },
  { id: "w-buffalo-wings", name: "버팔로윙", category: "고기·계란", cuisine: "양식", amount: "6개", kcal: 520, protein: 32, carbs: 12, fat: 38 },
  { id: "w-bbq-ribs", name: "바비큐폭립", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 720, protein: 40, carbs: 30, fat: 48 },
  { id: "w-pulled-pork", name: "풀드포크", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 520, protein: 34, carbs: 22, fat: 32 },
  { id: "w-meatball-tomato", name: "미트볼토마토", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 460, protein: 28, carbs: 24, fat: 28 },
  { id: "w-quiche-lorraine", name: "키슈로렌", category: "고기·계란", cuisine: "양식", amount: "1조각", kcal: 420, protein: 16, carbs: 26, fat: 28 },
  { id: "w-frittata", name: "프리타타", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 340, protein: 20, carbs: 10, fat: 24 },
  { id: "w-shakshuka", name: "샥슈카", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 360, protein: 18, carbs: 20, fat: 24 },
  { id: "w-beef-wellington", name: "비프웰링턴", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 720, protein: 40, carbs: 34, fat: 46 },
  { id: "w-lamb-chop", name: "램찹", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 560, protein: 38, carbs: 4, fat: 44 },
  { id: "w-veal-milanese", name: "송아지밀라네제", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 600, protein: 36, carbs: 34, fat: 34 },
  { id: "w-pork-schnitzel", name: "포크슈니첼", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 580, protein: 32, carbs: 34, fat: 34 },
  { id: "w-caprese-panini", name: "카프레제파니니", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 500, protein: 20, carbs: 48, fat: 26 },
  { id: "w-bruschetta", name: "브루스케타", category: "빵·간식", cuisine: "양식", amount: "3조각", kcal: 280, protein: 8, carbs: 34, fat: 12 },
  { id: "w-focaccia", name: "포카치아", category: "빵·간식", cuisine: "양식", amount: "1조각", kcal: 260, protein: 6, carbs: 36, fat: 10 },
  { id: "w-garlic-bread", name: "갈릭브레드", category: "빵·간식", cuisine: "양식", amount: "2조각", kcal: 320, protein: 7, carbs: 40, fat: 15 },
  { id: "w-bagel-cream-cheese", name: "베이글크림치즈", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 420, protein: 14, carbs: 58, fat: 15 },
  { id: "w-croissant-w", name: "크루아상(양식)", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 280, protein: 6, carbs: 30, fat: 15 },
  { id: "w-pain-au-chocolat", name: "뺑오쇼콜라", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 320, protein: 6, carbs: 34, fat: 18 },
  { id: "w-burrito", name: "부리또", category: "밥·면", cuisine: "양식", amount: "1개", kcal: 680, protein: 28, carbs: 78, fat: 28 },
  { id: "w-taco-w", name: "타코", category: "빵·간식", cuisine: "양식", amount: "2개", kcal: 420, protein: 20, carbs: 40, fat: 20 },
  { id: "w-quesadilla", name: "케사디아", category: "빵·간식", cuisine: "양식", amount: "1인분", kcal: 560, protein: 24, carbs: 46, fat: 30 },
  { id: "w-fajita", name: "파히타", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 620, protein: 32, carbs: 50, fat: 30 },
  { id: "w-nachos", name: "나쵸", category: "빵·간식", cuisine: "양식", amount: "1접시", kcal: 620, protein: 18, carbs: 58, fat: 36 },
  { id: "w-enchilada", name: "엔칠라다", category: "밥·면", cuisine: "양식", amount: "2개", kcal: 560, protein: 24, carbs: 48, fat: 28 },
  { id: "w-chili-con-carne", name: "칠리콘카르네", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 440, protein: 28, carbs: 34, fat: 22 },
  { id: "w-guacamole", name: "과카몰리", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 220, protein: 3, carbs: 12, fat: 19 },
  { id: "w-coleslaw", name: "코울슬로", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 180, protein: 2, carbs: 14, fat: 13 },
  { id: "w-lobster-roll", name: "랍스터롤", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 480, protein: 24, carbs: 40, fat: 24 },
  { id: "w-clam-linguine", name: "클램링귀네", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 560, protein: 24, carbs: 72, fat: 18 },
  { id: "w-penne-arrabbiata", name: "펜네아라비아타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 540, protein: 15, carbs: 82, fat: 15 },
  { id: "w-mushroom-cream-pasta", name: "버섯크림파스타", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 680, protein: 18, carbs: 76, fat: 32 },
  { id: "w-spinach-ricotta-ravioli", name: "시금치리코타라비올리", category: "밥·면", cuisine: "양식", amount: "1접시", kcal: 520, protein: 20, carbs: 62, fat: 22 },
  { id: "w-cannelloni", name: "카넬로니", category: "밥·면", cuisine: "양식", amount: "1인분", kcal: 560, protein: 26, carbs: 52, fat: 28 },
  { id: "w-eggplant-parmigiana", name: "가지파르미지아나", category: "채소·반찬", cuisine: "양식", amount: "1인분", kcal: 440, protein: 18, carbs: 30, fat: 28 },
  { id: "w-caponata", name: "카포나타", category: "채소·반찬", cuisine: "양식", amount: "1접시", kcal: 240, protein: 4, carbs: 24, fat: 15 },
  { id: "w-antipasto-platter", name: "안티파스토플래터", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 420, protein: 22, carbs: 14, fat: 32 },
  { id: "w-steak-frites", name: "스테이크프리트", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 780, protein: 44, carbs: 40, fat: 50 },
  { id: "w-coq-au-vin", name: "코코뱅", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 520, protein: 38, carbs: 16, fat: 32 },
  { id: "w-duck-confit", name: "덕콩피", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 560, protein: 36, carbs: 6, fat: 44 },
  { id: "w-cassoulet", name: "카술레", category: "국·찌개", cuisine: "양식", amount: "1인분", kcal: 620, protein: 32, carbs: 44, fat: 34 },
  { id: "w-osso-buco", name: "오소부코", category: "고기·계란", cuisine: "양식", amount: "1인분", kcal: 580, protein: 40, carbs: 18, fat: 36 },
  { id: "w-beef-bourguignon", name: "뵈프부르기뇽", category: "국·찌개", cuisine: "양식", amount: "1인분", kcal: 540, protein: 36, carbs: 20, fat: 32 },
  { id: "w-caprese-skewer", name: "카프레제꼬치", category: "채소·반찬", cuisine: "양식", amount: "3꼬치", kcal: 220, protein: 12, carbs: 8, fat: 16 },
  { id: "w-cream-of-broccoli", name: "브로콜리크림수프", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 260, protein: 8, carbs: 20, fat: 16 },
  { id: "w-gazpacho", name: "가스파초", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 140, protein: 4, carbs: 18, fat: 6 },
  { id: "w-lobster-bisque", name: "랍스터비스크", category: "국·찌개", cuisine: "양식", amount: "1그릇", kcal: 340, protein: 16, carbs: 18, fat: 22 },
  { id: "w-chicken-wrap", name: "치킨랩", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 480, protein: 28, carbs: 42, fat: 22 },
  { id: "w-poke-bowl", name: "포케볼", category: "밥·면", cuisine: "양식", amount: "1그릇", kcal: 520, protein: 28, carbs: 62, fat: 16 },
  { id: "w-buddha-bowl", name: "부다볼", category: "채소·반찬", cuisine: "양식", amount: "1그릇", kcal: 480, protein: 18, carbs: 58, fat: 20 },
  { id: "w-caesar-wrap", name: "시저랩", category: "빵·간식", cuisine: "양식", amount: "1개", kcal: 460, protein: 22, carbs: 40, fat: 24 },

  // ── 기타 아시아(동남아·인도·중동)
  { id: "w-pad-thai", name: "팟타이", category: "밥·면", cuisine: "아시아", amount: "1접시", kcal: 560, protein: 20, carbs: 74, fat: 20 },
  { id: "w-pad-see-ew", name: "팟씨유", category: "밥·면", cuisine: "아시아", amount: "1접시", kcal: 580, protein: 20, carbs: 76, fat: 22 },
  { id: "w-pad-kra-pao", name: "팟카파오", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 620, protein: 26, carbs: 72, fat: 26 },
  { id: "w-tom-yum-goong", name: "똠얌꿍", category: "국·찌개", cuisine: "아시아", amount: "1그릇", kcal: 280, protein: 22, carbs: 18, fat: 14 },
  { id: "w-tom-kha-gai", name: "똠카가이", category: "국·찌개", cuisine: "아시아", amount: "1그릇", kcal: 340, protein: 20, carbs: 16, fat: 22 },
  { id: "w-green-curry", name: "그린커리", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 420, protein: 22, carbs: 24, fat: 26 },
  { id: "w-red-curry", name: "레드커리", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 420, protein: 22, carbs: 24, fat: 26 },
  { id: "w-massaman-curry", name: "마사만커리", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 480, protein: 24, carbs: 32, fat: 28 },
  { id: "w-panang-curry", name: "파낭커리", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 460, protein: 24, carbs: 24, fat: 30 },
  { id: "w-khao-pad", name: "카오팟", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 560, protein: 18, carbs: 78, fat: 18 },
  { id: "w-som-tam", name: "쏨땀", category: "채소·반찬", cuisine: "아시아", amount: "1접시", kcal: 180, protein: 6, carbs: 26, fat: 6 },
  { id: "w-mango-sticky-rice", name: "망고스티키라이스", category: "빵·간식", cuisine: "아시아", amount: "1인분", kcal: 380, protein: 5, carbs: 68, fat: 11 },
  { id: "w-thai-fish-cake", name: "타이피시케이크", category: "생선·해산물", cuisine: "아시아", amount: "4개", kcal: 320, protein: 20, carbs: 20, fat: 18 },
  { id: "w-satay-thai", name: "치킨사테", category: "고기·계란", cuisine: "아시아", amount: "4꼬치", kcal: 360, protein: 28, carbs: 12, fat: 22 },
  { id: "w-thai-milk-tea", name: "타이밀크티", category: "음료", cuisine: "아시아", amount: "1잔", kcal: 220, protein: 4, carbs: 38, fat: 6 },
  { id: "w-pho-bo", name: "쌀국수(소고기)", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 440, protein: 28, carbs: 62, fat: 8 },
  { id: "w-pho-ga", name: "쌀국수(닭고기)", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 400, protein: 26, carbs: 60, fat: 6 },
  { id: "w-bun-cha", name: "분짜", category: "밥·면", cuisine: "아시아", amount: "1인분", kcal: 560, protein: 26, carbs: 66, fat: 20 },
  { id: "w-banh-mi", name: "반미", category: "빵·간식", cuisine: "아시아", amount: "1개", kcal: 480, protein: 20, carbs: 56, fat: 20 },
  { id: "w-goi-cuon", name: "고이꾸언", category: "채소·반찬", cuisine: "아시아", amount: "2개", kcal: 180, protein: 10, carbs: 26, fat: 4 },
  { id: "w-cha-gio", name: "짜조", category: "빵·간식", cuisine: "아시아", amount: "3개", kcal: 320, protein: 12, carbs: 30, fat: 18 },
  { id: "w-bun-bo-hue", name: "분보후에", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 500, protein: 28, carbs: 62, fat: 14 },
  { id: "w-com-tam", name: "껌땀", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 620, protein: 26, carbs: 78, fat: 22 },
  { id: "w-vietnamese-coffee", name: "베트남연유커피", category: "음료", cuisine: "아시아", amount: "1잔", kcal: 180, protein: 4, carbs: 26, fat: 6 },
  { id: "w-butter-chicken", name: "버터치킨", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 560, protein: 32, carbs: 20, fat: 38 },
  { id: "w-chicken-tikka-masala", name: "치킨티카마살라", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 540, protein: 34, carbs: 22, fat: 34 },
  { id: "w-tandoori-chicken", name: "탄두리치킨", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 420, protein: 40, carbs: 8, fat: 26 },
  { id: "w-chicken-biryani", name: "치킨비리야니", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 680, protein: 28, carbs: 82, fat: 26 },
  { id: "w-mutton-biryani", name: "머튼비리야니", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 720, protein: 30, carbs: 82, fat: 30 },
  { id: "w-naan", name: "난", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 280, protein: 8, carbs: 48, fat: 6 },
  { id: "w-garlic-naan", name: "갈릭난", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 320, protein: 8, carbs: 48, fat: 11 },
  { id: "w-samosa", name: "사모사", category: "빵·간식", cuisine: "아시아", amount: "2개", kcal: 300, protein: 6, carbs: 34, fat: 16 },
  { id: "w-dal-curry", name: "달(렌틸커리)", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 300, protein: 16, carbs: 40, fat: 9 },
  { id: "w-palak-paneer", name: "팔락파니르", category: "채소·반찬", cuisine: "아시아", amount: "1인분", kcal: 380, protein: 18, carbs: 18, fat: 26 },
  { id: "w-chana-masala", name: "차나마살라", category: "국·찌개", cuisine: "아시아", amount: "1인분", kcal: 340, protein: 14, carbs: 44, fat: 12 },
  { id: "w-rogan-josh", name: "로건조쉬", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 520, protein: 32, carbs: 16, fat: 36 },
  { id: "w-aloo-gobi", name: "알루고비", category: "채소·반찬", cuisine: "아시아", amount: "1인분", kcal: 260, protein: 7, carbs: 32, fat: 12 },
  { id: "w-lamb-vindaloo", name: "램빈달루", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 540, protein: 32, carbs: 20, fat: 36 },
  { id: "w-mango-lassi", name: "망고라씨", category: "음료", cuisine: "아시아", amount: "1잔", kcal: 220, protein: 6, carbs: 38, fat: 5 },
  { id: "w-masala-chai", name: "마살라짜이", category: "음료", cuisine: "아시아", amount: "1잔", kcal: 120, protein: 4, carbs: 18, fat: 4 },
  { id: "w-gulab-jamun", name: "굴랍자문", category: "빵·간식", cuisine: "아시아", amount: "2개", kcal: 300, protein: 4, carbs: 52, fat: 10 },
  { id: "w-roti", name: "로티", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 180, protein: 6, carbs: 34, fat: 3 },
  { id: "w-nasi-goreng", name: "나시고랭", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 600, protein: 20, carbs: 78, fat: 22 },
  { id: "w-mie-goreng", name: "미고랭", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 580, protein: 18, carbs: 76, fat: 22 },
  { id: "w-satay-indo", name: "사테아얌", category: "고기·계란", cuisine: "아시아", amount: "4꼬치", kcal: 360, protein: 28, carbs: 12, fat: 22 },
  { id: "w-rendang", name: "렌당", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 560, protein: 32, carbs: 16, fat: 40 },
  { id: "w-gado-gado", name: "가도가도", category: "채소·반찬", cuisine: "아시아", amount: "1접시", kcal: 380, protein: 14, carbs: 34, fat: 22 },
  { id: "w-laksa", name: "락사", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 560, protein: 24, carbs: 60, fat: 26 },
  { id: "w-hainanese-chicken-rice", name: "하이난치킨라이스", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 600, protein: 30, carbs: 72, fat: 22 },
  { id: "w-char-kway-teow", name: "차퀘이테우", category: "밥·면", cuisine: "아시아", amount: "1접시", kcal: 620, protein: 22, carbs: 74, fat: 26 },
  { id: "w-roti-canai", name: "로티차나이", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 300, protein: 6, carbs: 38, fat: 14 },
  { id: "w-bak-kut-teh", name: "바쿠테", category: "국·찌개", cuisine: "아시아", amount: "1그릇", kcal: 420, protein: 30, carbs: 12, fat: 28 },
  { id: "w-doner-kebab", name: "케밥(도네르)", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 620, protein: 34, carbs: 48, fat: 32 },
  { id: "w-shish-kebab", name: "쉬쉬케밥", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 480, protein: 36, carbs: 12, fat: 30 },
  { id: "w-shawarma", name: "샤와르마", category: "빵·간식", cuisine: "아시아", amount: "1개", kcal: 560, protein: 30, carbs: 46, fat: 28 },
  { id: "w-hummus", name: "후무스", category: "채소·반찬", cuisine: "아시아", amount: "1접시", kcal: 280, protein: 10, carbs: 24, fat: 16 },
  { id: "w-falafel", name: "팔라펠", category: "채소·반찬", cuisine: "아시아", amount: "4개", kcal: 340, protein: 12, carbs: 32, fat: 18 },
  { id: "w-tabbouleh", name: "타불레", category: "채소·반찬", cuisine: "아시아", amount: "1접시", kcal: 200, protein: 5, carbs: 26, fat: 9 },
  { id: "w-baba-ganoush", name: "바바가누쉬", category: "채소·반찬", cuisine: "아시아", amount: "1접시", kcal: 220, protein: 5, carbs: 16, fat: 16 },
  { id: "w-lamb-kofta", name: "램코프타", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 460, protein: 30, carbs: 10, fat: 32 },
  { id: "w-pita-bread", name: "피타브레드", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 180, protein: 6, carbs: 34, fat: 2 },
  { id: "w-turkish-pide", name: "터키피데", category: "빵·간식", cuisine: "아시아", amount: "1인분", kcal: 520, protein: 22, carbs: 58, fat: 22 },
  { id: "w-dolma", name: "돌마", category: "채소·반찬", cuisine: "아시아", amount: "4개", kcal: 220, protein: 5, carbs: 30, fat: 9 },
  { id: "w-khao-soi", name: "카오소이", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 620, protein: 26, carbs: 60, fat: 32 },
  { id: "w-larb", name: "랍(태국)", category: "고기·계란", cuisine: "아시아", amount: "1접시", kcal: 320, protein: 26, carbs: 12, fat: 18 },
  { id: "w-thai-basil-fried-rice", name: "카파오 볶음밥", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 600, protein: 24, carbs: 76, fat: 22 },
  { id: "w-vietnamese-spring-roll", name: "월남쌈", category: "채소·반찬", cuisine: "아시아", amount: "3개", kcal: 200, protein: 10, carbs: 30, fat: 4 },
  { id: "w-cao-lau", name: "까올라우", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 520, protein: 24, carbs: 66, fat: 18 },
  { id: "w-mi-quang", name: "미꽝", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 540, protein: 24, carbs: 64, fat: 20 },
  { id: "w-paneer-tikka", name: "파니르티카", category: "채소·반찬", cuisine: "아시아", amount: "1인분", kcal: 380, protein: 20, carbs: 14, fat: 28 },
  { id: "w-keema-curry", name: "키마커리", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 480, protein: 30, carbs: 18, fat: 32 },
  { id: "w-fish-curry-indian", name: "인도생선커리", category: "생선·해산물", cuisine: "아시아", amount: "1인분", kcal: 420, protein: 30, carbs: 16, fat: 26 },
  { id: "w-prawn-curry", name: "새우커리", category: "생선·해산물", cuisine: "아시아", amount: "1인분", kcal: 400, protein: 28, carbs: 16, fat: 24 },
  { id: "w-dosa", name: "도사", category: "빵·간식", cuisine: "아시아", amount: "1장", kcal: 280, protein: 8, carbs: 44, fat: 8 },
  { id: "w-idli", name: "이들리", category: "밥·면", cuisine: "아시아", amount: "3개", kcal: 220, protein: 8, carbs: 42, fat: 2 },
  { id: "w-vada", name: "바다(인도)", category: "빵·간식", cuisine: "아시아", amount: "2개", kcal: 260, protein: 8, carbs: 28, fat: 13 },
  { id: "w-pani-puri", name: "파니푸리", category: "빵·간식", cuisine: "아시아", amount: "6개", kcal: 240, protein: 6, carbs: 36, fat: 8 },
  { id: "w-nasi-lemak", name: "나시르막", category: "밥·면", cuisine: "아시아", amount: "1그릇", kcal: 620, protein: 20, carbs: 72, fat: 28 },
  { id: "w-thai-omelette", name: "카이찌여우(태국오믈렛)", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 340, protein: 16, carbs: 8, fat: 26 },
  { id: "w-adobo", name: "치킨아도보", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 460, protein: 34, carbs: 14, fat: 28 },
  { id: "w-lumpia", name: "룸피아", category: "빵·간식", cuisine: "아시아", amount: "3개", kcal: 300, protein: 10, carbs: 30, fat: 16 },
  { id: "w-sinigang", name: "시니강", category: "국·찌개", cuisine: "아시아", amount: "1그릇", kcal: 300, protein: 24, carbs: 20, fat: 14 },
  { id: "w-menemen", name: "터키식 계란요리(멘멘)", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 340, protein: 16, carbs: 18, fat: 22 },
  { id: "w-manti", name: "만티(터키만두)", category: "밥·면", cuisine: "아시아", amount: "1인분", kcal: 480, protein: 20, carbs: 56, fat: 20 },
  { id: "w-iskender-kebab", name: "이스켄데르케밥", category: "고기·계란", cuisine: "아시아", amount: "1인분", kcal: 720, protein: 38, carbs: 46, fat: 42 },
  { id: "w-lentil-soup-turkish", name: "터키렌틸수프", category: "국·찌개", cuisine: "아시아", amount: "1그릇", kcal: 240, protein: 12, carbs: 34, fat: 6 },
  { id: "w-thai-coconut-icecream", name: "타이코코넛아이스크림", category: "빵·간식", cuisine: "아시아", amount: "1개", kcal: 240, protein: 3, carbs: 32, fat: 12 },

  // ── 그외(디저트·음료·기타)
  { id: "w-tiramisu", name: "티라미수", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 380, protein: 7, carbs: 40, fat: 22 },
  { id: "w-crepe", name: "크레페", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 320, protein: 8, carbs: 42, fat: 13 },
  { id: "w-macaron", name: "마카롱", category: "빵·간식", cuisine: "그외", amount: "2개", kcal: 180, protein: 3, carbs: 26, fat: 8 },
  { id: "w-gelato", name: "젤라또", category: "빵·간식", cuisine: "그외", amount: "1컵", kcal: 240, protein: 5, carbs: 32, fat: 11 },
  { id: "w-baklava", name: "바클라바", category: "빵·간식", cuisine: "그외", amount: "2개", kcal: 340, protein: 5, carbs: 40, fat: 19 },
  { id: "w-egg-tart", name: "에그타르트", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 210, protein: 4, carbs: 24, fat: 11 },
  { id: "w-panna-cotta", name: "판나코타", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 300, protein: 5, carbs: 28, fat: 19 },
  { id: "w-creme-brulee", name: "크렘브륄레", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 340, protein: 6, carbs: 30, fat: 22 },
  { id: "w-cheesecake", name: "치즈케이크", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 400, protein: 8, carbs: 34, fat: 26 },
  { id: "w-brownie", name: "브라우니", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 340, protein: 5, carbs: 42, fat: 18 },
  { id: "w-macaroon-coconut", name: "코코넛마카룬", category: "빵·간식", cuisine: "그외", amount: "2개", kcal: 200, protein: 3, carbs: 24, fat: 11 },
  { id: "w-churros-w", name: "츄러스(양식)", category: "빵·간식", cuisine: "그외", amount: "3개", kcal: 360, protein: 5, carbs: 44, fat: 18 },
  { id: "w-flan", name: "플란", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 280, protein: 7, carbs: 40, fat: 10 },
  { id: "w-apple-pie", name: "애플파이", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 380, protein: 4, carbs: 52, fat: 18 },
  { id: "w-donut", name: "도넛(양식)", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 300, protein: 4, carbs: 38, fat: 16 },
  { id: "w-eclair", name: "에클레어", category: "빵·간식", cuisine: "그외", amount: "1개", kcal: 280, protein: 5, carbs: 30, fat: 16 },
  { id: "w-madeleine", name: "마들렌", category: "빵·간식", cuisine: "그외", amount: "2개", kcal: 200, protein: 4, carbs: 24, fat: 10 },
  { id: "w-pavlova", name: "파블로바", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 260, protein: 3, carbs: 42, fat: 10 },
  { id: "w-halva", name: "할바", category: "빵·간식", cuisine: "그외", amount: "1조각", kcal: 320, protein: 5, carbs: 44, fat: 15 },
  { id: "w-mochi-icecream", name: "모찌아이스크림", category: "빵·간식", cuisine: "그외", amount: "2개", kcal: 220, protein: 3, carbs: 36, fat: 8 },
  { id: "w-affogato", name: "아포가토", category: "빵·간식", cuisine: "그외", amount: "1잔", kcal: 200, protein: 4, carbs: 22, fat: 11 },
  { id: "w-gelato-pistachio", name: "피스타치오젤라또", category: "빵·간식", cuisine: "그외", amount: "1컵", kcal: 260, protein: 6, carbs: 30, fat: 13 },
  { id: "w-mojito", name: "모히토", category: "음료", cuisine: "그외", amount: "1잔", kcal: 160, protein: 0, carbs: 20, fat: 0 },
  { id: "w-sangria", name: "상그리아", category: "음료", cuisine: "그외", amount: "1잔", kcal: 180, protein: 0, carbs: 22, fat: 0 },
  { id: "w-martini", name: "마티니", category: "음료", cuisine: "그외", amount: "1잔", kcal: 140, protein: 0, carbs: 2, fat: 0 },
  { id: "w-margarita", name: "마가리타", category: "음료", cuisine: "그외", amount: "1잔", kcal: 220, protein: 0, carbs: 24, fat: 0 },
  { id: "w-pina-colada", name: "피나콜라다", category: "음료", cuisine: "그외", amount: "1잔", kcal: 320, protein: 2, carbs: 40, fat: 8 },
  { id: "w-kombucha", name: "콤부차", category: "음료", cuisine: "그외", amount: "1잔", kcal: 60, protein: 0, carbs: 14, fat: 0 },
  { id: "w-bubble-tea", name: "버블티", category: "음료", cuisine: "그외", amount: "1잔", kcal: 320, protein: 3, carbs: 62, fat: 6 },
  { id: "w-espresso", name: "에스프레소", category: "음료", cuisine: "그외", amount: "1잔", kcal: 5, protein: 0, carbs: 1, fat: 0 },
  { id: "w-hot-chocolate", name: "핫초콜릿", category: "음료", cuisine: "그외", amount: "1잔", kcal: 240, protein: 8, carbs: 32, fat: 10 },
  { id: "w-smoothie-berry", name: "베리스무디", category: "음료", cuisine: "그외", amount: "1잔", kcal: 220, protein: 5, carbs: 44, fat: 3 },
  { id: "w-green-smoothie", name: "그린스무디", category: "음료", cuisine: "그외", amount: "1잔", kcal: 180, protein: 5, carbs: 34, fat: 3 },
  { id: "w-granola", name: "그래놀라", category: "빵·간식", cuisine: "그외", amount: "1인분", kcal: 280, protein: 7, carbs: 40, fat: 11 },
  { id: "w-cornflakes", name: "콘플레이크", category: "빵·간식", cuisine: "그외", amount: "1그릇", kcal: 220, protein: 5, carbs: 46, fat: 3 },
  { id: "w-muesli", name: "뮤즐리", category: "빵·간식", cuisine: "그외", amount: "1그릇", kcal: 300, protein: 9, carbs: 48, fat: 9 },
  { id: "w-acai-bowl", name: "아사이볼", category: "과일", cuisine: "그외", amount: "1그릇", kcal: 340, protein: 6, carbs: 58, fat: 11 },
  { id: "w-fruit-salad-w", name: "과일샐러드", category: "과일", cuisine: "그외", amount: "1그릇", kcal: 160, protein: 2, carbs: 38, fat: 1 },
  { id: "w-camembert", name: "카망베르치즈", category: "유제품", cuisine: "그외", amount: "30g", kcal: 90, protein: 6, carbs: 1, fat: 7 },
  { id: "w-brie-cheese", name: "브리치즈", category: "유제품", cuisine: "그외", amount: "30g", kcal: 100, protein: 6, carbs: 1, fat: 8 },
  { id: "w-cheddar-cheese", name: "체다치즈", category: "유제품", cuisine: "그외", amount: "30g", kcal: 115, protein: 7, carbs: 1, fat: 9 },
  { id: "w-whey-protein", name: "웨이프로틴", category: "단백질·보충", cuisine: "그외", amount: "1스쿱", kcal: 120, protein: 24, carbs: 3, fat: 2 },
  { id: "w-bcaa-drink", name: "BCAA음료", category: "단백질·보충", cuisine: "그외", amount: "1잔", kcal: 30, protein: 5, carbs: 2, fat: 0 },
  { id: "w-protein-pancake", name: "프로틴팬케이크", category: "단백질·보충", cuisine: "그외", amount: "3장", kcal: 340, protein: 28, carbs: 40, fat: 8 },
  { id: "w-nut-mix", name: "믹스넛", category: "빵·간식", cuisine: "그외", amount: "30g", kcal: 190, protein: 6, carbs: 7, fat: 16 },
  { id: "w-trail-mix", name: "트레일믹스", category: "빵·간식", cuisine: "그외", amount: "40g", kcal: 200, protein: 6, carbs: 20, fat: 12 },
  { id: "w-peanut-butter", name: "피넛버터", category: "빵·간식", cuisine: "그외", amount: "2큰술", kcal: 190, protein: 8, carbs: 6, fat: 16 },
  { id: "w-hummus-cracker", name: "후무스&크래커", category: "빵·간식", cuisine: "그외", amount: "1인분", kcal: 260, protein: 8, carbs: 28, fat: 14 },
  { id: "w-turkish-delight", name: "터키쉬딜라이트", category: "빵·간식", cuisine: "그외", amount: "3개", kcal: 180, protein: 1, carbs: 44, fat: 1 },
];
