import { randomUUID, createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { expect, test } from "vitest";
import { hasDbCreds, makeClient } from "./db";

test.skipIf(!hasDbCreds)("independent trainer: pass, explicit consent, masking, RLS, revocation and queued notification", async () => {
  const db = makeClient();
  await db.connect();
  const trainer = randomUUID(), member = randomUUID(), stranger = randomUUID(), admin = randomUUID();
  const email = (id: string) => `pt-test-${id}@example.com`;
  async function as(id: string) {
    await db.query("reset role");
    await db.query("select set_config('request.jwt.claims',$1,true)", [JSON.stringify({ sub: id, email: email(id), role: "authenticated" })]);
    await db.query("set local role authenticated");
  }
  async function denied(sql: string, args: unknown[] = []) {
    await db.query("savepoint denied");
    let failed = false;
    try { await db.query(sql, args); } catch { failed = true; }
    await db.query("rollback to savepoint denied");
    expect(failed, sql).toBe(true);
  }
  const hash = (value: string) => createHash("sha256").update(value).digest("hex");
  try {
    await db.query("begin");
    await db.query(readFileSync("supabase/migrations/202609220002_independent_trainers.sql", "utf8"));
    await db.query(readFileSync("supabase/migrations/202609250002_trainer_member_detail.sql", "utf8"));
    for (const id of [trainer, member, stranger, admin]) {
      await db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,$2,'{}')", [id,email(id)]);
    }
    await db.query("insert into public.admins(email) values($1)", [email(admin)]);
    await db.query(readFileSync("supabase/migrations/202609220001_pet_visibility.sql", "utf8"));
    await db.query("delete from app_settings where key='debug.pet'");
    await as(admin);
    expect((await db.query("select debug_feature_enabled('pet') enabled")).rows[0].enabled).toBe(false);
    await db.query("reset role");
    await db.query("insert into app_settings(key,value) values('debug.pet', to_jsonb('public'::text))");
    await as(stranger);
    expect((await db.query("select debug_feature_enabled('pet') enabled")).rows[0].enabled).toBe(true);
    await db.query("reset role");
    await db.query("update app_settings set value='false'::jsonb where key='debug.pet'");
    await as(trainer);
    expect((await db.query("select debug_feature_enabled('pet') enabled")).rows[0].enabled).toBe(false);
    await db.query("select public.pt_request_pass('테스트 트레이너','01012345678')");
    expect((await db.query("select public.pt_has_pass() as yes")).rows[0].yes).toBe(false);
    await denied("select public.pt_admin_pass($1,(now() at time zone 'Asia/Seoul')::date,(now() at time zone 'Asia/Seoul')::date+30,15,true)", [trainer]);
    await denied("update public.pt_passes set status='active' where trainer_id=$1", [trainer]);
    await denied("select public.pt_create_invite($1,'01087654321','ATA','https://example.com/invite')", [hash("a")]);
    await as(admin);
    await db.query("select public.pt_admin_pass($1,(now() at time zone 'Asia/Seoul')::date+1,(now() at time zone 'Asia/Seoul')::date+30,15,true)", [trainer]);
    await as(trainer);
    expect((await db.query("select public.pt_has_pass() as yes")).rows[0].yes).toBe(false);
    await as(admin);
    await db.query("select public.pt_admin_pass($1,(now() at time zone 'Asia/Seoul')::date-1,(now() at time zone 'Asia/Seoul')::date+30,15,true)", [trainer]);
    await as(trainer);
    await db.query("select public.pt_create_invite($1,'01087654321','ATA','https://example.com/invite')", [hash("a")]);
    expect((await db.query("select count(*)::int n from public.pt_links")).rows[0].n).toBe(0);
    await as(member);
    const link = (await db.query("select public.pt_accept_invite($1,true,false,false,false) id", [hash("a")])).rows[0].id;
    await denied("select public.pt_accept_invite($1,true,true,true,true)", [hash("a")]);
    await as(stranger);
    expect((await db.query("select public.pt_member_report($1) report", [link])).rows[0].report).toBeNull();
    await denied("select public.pt_update_sharing($1,true,true,true,true)", [link]);
    await denied("select public.pt_disconnect($1)", [link]);
    await db.query("reset role");
    await db.query("insert into user_routines(user_id,splits,variant_id,start_date) values($1,3,'manual',(now() at time zone 'Asia/Seoul')::date)", [member]);
    const exercise = (await db.query("insert into routine_exercises(user_id,focus,exercise_id,equipment,day_index) values($1,'chest','bench-press','barbell',0) returning id,updated_at::text", [member])).rows[0];
    const patch = {exerciseId:"bench-press",equipment:"barbell",sets:4,reps:8,weightKg:20};
    await as(trainer);
    expect((await db.query("select pt_prescribe_today($1,$2,'chest',0,'bench-press',$3,'오늘 처방') ok", [link,member,patch])).rows[0].ok).toBe(false);
    await as(member);
    await db.query("select pt_update_sharing($1,true,false,false,true)", [link]);
    await as(trainer);
    expect((await db.query("select pt_prescribe_today($1,$2,'chest',0,'bench-press',$3,'오늘 처방') ok", [link,member,patch])).rows[0].ok).toBe(true);
    await db.query("reset role");
    expect((await db.query("select sets from routine_exercises where id=$1", [exercise.id])).rows[0].sets).toBe(3);
    expect((await db.query("select sets from daily_plan where user_id=$1", [member])).rows[0].sets).toBe(4);
    await as(trainer);
    expect((await db.query("select pt_prescribe_exercise($1,$2,$3,$4,$5,'영구 처방') ok", [link,member,exercise.id,exercise.updated_at,{...patch,sets:5}])).rows[0].ok).toBe(true);
    await db.query("reset role");
    expect((await db.query("select sets from daily_plan where user_id=$1", [member])).rows[0].sets).toBe(4);
    await as(member);
    await db.query("select pt_update_sharing($1,true,false,false,false)", [link]);
    await as(trainer);
    const report = (await db.query("select public.pt_member_report($1) report", [link])).rows[0].report;
    const detail = (await db.query("select public.pt_member_detail($1,$2,(now() at time zone 'Asia/Seoul')::date-6,(now() at time zone 'Asia/Seoul')::date) report", [link,member])).rows[0].report;
    expect(detail.sharing).toEqual({workout:true,diet:false,body:false,prescription:false});
    expect(detail.exercises).toEqual([]);
    expect(report.workout).not.toBeNull();
    expect(report.diet).toBeNull(); expect(report.body).toBeNull(); expect(report.prescription).toBe(false);
    await denied("select public.pt_update_sharing($1,true,true,true,true)", [link]);
    await as(member);
    await db.query("select public.pt_update_sharing($1,false,true,true,false)", [link]);
    await as(trainer);
    const masked = (await db.query("select public.pt_member_report($1) report", [link])).rows[0].report;
    expect(masked.workout).toBeNull(); expect(masked.diet).not.toBeNull(); expect(masked.body).not.toBeNull();
    await as(member);
    const note = (await db.query("select public.pt_disconnect($1) id", [link])).rows[0].id;
    expect(note).toBeTruthy();
    await as(trainer);
    expect((await db.query("select pt_prescribe_today($1,$2,'chest',0,'bench-press',$3,'차단 확인') ok", [link,member,patch])).rows[0].ok).toBe(false);
    await as(member);
    const outbox = (await db.query("select kind,channel,status from public.pt_notifications where id=$1", [note])).rows[0];
    expect(outbox).toEqual({ kind: "disconnect", channel: "ATA", status: "queued" });
    expect((await db.query("select public.pt_disconnect($1) id", [link])).rows[0].id).toBeNull();
    await denied("select public.pt_update_sharing($1,true,true,true,true)", [link]);
    await as(trainer);
    expect((await db.query("select public.pt_member_report($1) report", [link])).rows[0].report).toBeNull();
    expect((await db.query("select count(*)::int n from public.pt_links")).rows[0].n).toBe(0);
    await db.query("select public.pt_create_invite($1,'01087654321','LMS','https://example.com/new')", [hash("b")]);
    expect((await db.query("select public.pt_member_report($1) report", [link])).rows[0].report).toBeNull();
    await as(member);
    await db.query("select public.pt_accept_invite($1,false,false,false,false)", [hash("b")]);
    await as(trainer);
    expect((await db.query("select public.pt_member_report($1) report", [link])).rows[0].report.workout).toBeNull();
    await db.query("reset role");
    expect((await db.query("select count(*)::int n from group_members where user_id=any($1::uuid[])", [[trainer,member]])).rows[0].n).toBe(0);
    const legacy = await db.query("select has_function_privilege('authenticated',oid,'execute') allowed from pg_proc where pronamespace='public'::regnamespace and proname in ('trainer_board','trainer_member_report','trainer_prescribe_today')");
    expect(legacy.rows.every(row => !row.allowed)).toBe(true);
  } finally { await db.query("rollback"); await db.end(); }
}, 90_000);