import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {pathToFileURL} from 'node:url';
import sharp from 'sharp';
const project=resolve('.');
const out=resolve('tools/media/imports/exercise-video-20260925/low-bar-anchored');
const guides=join(out,'tools/media/motion-guides');
mkdirSync(guides,{recursive:true});
mkdirSync(join(out,'tools/media/ai-guides'),{recursive:true});
mkdirSync(join(out,'public/exercise-guides/ai-v3'),{recursive:true});
const catalog=JSON.parse(readFileSync('tools/media/ai-guides/catalog.json','utf8'));
writeFileSync(join(out,'tools/media/ai-guides/catalog.json'),JSON.stringify(catalog.filter(x=>x.id==='low-bar-squat')));
await sharp(join(out,'sheet.png')).removeAlpha().jpeg({quality:96}).toFile(join(guides,'low-bar-squat.jpg'));
const generation=JSON.parse(readFileSync(join(out,'generation.json'),'utf8'));
writeFileSync(join(guides,'low-bar-squat.json'),JSON.stringify({prompt:generation.prompts.at(-1),equipment:'barbell',sources:['https://www.muscleandstrength.com/exercises/low-bar-back-squat'],panels:16,cycle:'reverse',cutout:true}));
process.chdir(out);
const {manageMotionGuides}=await import(pathToFileURL(join(project,'tools/media/manage-motion-guides.mjs')));
await manageMotionGuides('motion-build','low-bar-squat');
