/**
  * 운동 id → free-exercise-db(퍼블릭도메인, Unlicense) 운동 id 매핑.
  * 두 프레임(0/1.jpg)을 교차해 실제 시연 동작을 보여준다. jsdelivr CDN 로 로드.
  * 출처: https://github.com/yuhonas/free-exercise-db (The Unlicense)
  */
export const EXERCISE_PHOTO_DB: Record<string, string> = {
  "ab-rollout": "Barbell_Ab_Rollout",
  "arnold-press": "Arnold_Dumbbell_Press",
  "assisted-pull-up": "Band_Assisted_Pull-Up",
  "barbell-row": "Bent_Over_Barbell_Row",
  "bench-dip": "Weighted_Bench_Dip",
  "bench-press": "Barbell_Bench_Press_-_Medium_Grip",
  "biceps-curl": "Barbell_Curl",
  "box-squat": "Box_Squat",
  "bulgarian-split-squat": "Split_Squat_with_Dumbbells",
  "cable-crossover": "Cable_Crossover",
  "cable-crunch": "Cable_Crunch",
  "cable-kickback": "One-Legged_Cable_Kickback",
  "cable-lateral-raise": "Cable_Seated_Lateral_Raise",
  "cable-pull-through": "Pull_Through",
  "cable-rope-hammer-curl": "Cable_Hammer_Curls_-_Rope_Attachment",
  "chest-fly": "Dumbbell_Flyes",
  "chin-up": "Chin-Up",
  "close-grip-bench-press": "Close-Grip_Barbell_Bench_Press",
  "concentration-curl": "Standing_Concentration_Curl",
  "crunch": "Crunches",
  "deadlift": "Barbell_Deadlift",
  "decline-press": "Decline_Smith_Press",
  "dips": "Dips_-_Triceps_Version",
  "donkey-calf-raise": "Donkey_Calf_Raises",
  "drag-curl": "Drag_Curl",
  "dumbbell-pullover": "Bent-Arm_Dumbbell_Pullover",
  "ez-bar-curl": "EZ-Bar_Curl",
  "face-pull": "Face_Pull",
  "front-raise": "Front_Dumbbell_Raise",
  "front-squat": "Front_Barbell_Squat",
  "glute-bridge": "Butt_Lift_Bridge",
  "goblet-squat": "Goblet_Squat",
  "good-morning": "Good_Morning",
  "hack-squat": "Hack_Squat",
  "hammer-curl": "Hammer_Curls",
  "hanging-leg-raise": "Hanging_Leg_Raise",
  "hip-adduction": "Cable_Hip_Adduction",
  "hip-thrust": "Barbell_Hip_Thrust",
  "hyperextension": "Reverse_Hyperextension",
  "incline-cable-fly": "Incline_Dumbbell_Flyes",
  "incline-curl": "Incline_Dumbbell_Curl",
  "incline-press": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "inverted-row": "Inverted_Row",
  "lat-pulldown": "Wide-Grip_Lat_Pulldown",
  "lateral-raise": "Side_Lateral_Raise",
  "leg-curl": "Lying_Leg_Curls",
  "leg-extension": "Leg_Extensions",
  "leg-press": "Leg_Press",
  "low-row-machine": "Low_Pulley_Row_To_Neck",
  "lunge": "Dumbbell_Lunges",
  "machine-chest-press": "Cable_Chest_Press",
  "machine-rear-delt-fly": "Cable_Rear_Delt_Fly",
  "machine-shoulder-press": "Machine_Shoulder_Military_Press",
  "ohp": "Barbell_Shoulder_Press",
  "one-arm-dumbbell-row": "One-Arm_Dumbbell_Row",
  "overhead-triceps-extension": "Sled_Overhead_Triceps_Extension",
  "pallof-press": "Pallof_Press",
  "pec-deck": "Dumbbell_Flyes",
  "pistol-squat": "Kettlebell_Pistol_Squat",
  "plank": "Plank",
  "preacher-curl": "Preacher_Curl",
  "pull-up": "Pullups",
  "push-up": "Pushups",
  "rdl": "Romanian_Deadlift",
  "rear-delt-fly": "Cable_Rear_Delt_Fly",
  "reverse-crunch": "Reverse_Crunch",
  "reverse-curl": "Reverse_Barbell_Curl",
  "reverse-pec-deck": "Reverse_Machine_Flyes",
  "russian-twist": "Russian_Twist",
  "seated-cable-row": "Seated_Cable_Rows",
  "seated-calf-raise": "Seated_Calf_Raise",
  "seated-leg-curl": "Seated_Leg_Curl",
  "shrug": "Barbell_Shrug",
  "single-leg-leg-press": "Leg_Press",
  "sissy-squat": "Weighted_Sissy_Squat",
  "sit-up": "3_4_Sit-Up",
  "skull-crusher": "Lying_Triceps_Press",
  "smith-bench-press": "Smith_Machine_Bench_Press",
  "smith-squat": "Smith_Machine_Squat",
  "squat": "Barbell_Squat",
  "standing-cable-curl": "Standing_Biceps_Cable_Curl",
  "standing-calf-raise": "Rocking_Standing_Calf_Raise",
  "step-up": "Step-up_with_Knee_Raise",
  "stiff-leg-deadlift": "Stiff-Legged_Barbell_Deadlift",
  "straight-arm-pulldown": "Straight-Arm_Pulldown",
  "sumo-deadlift": "Sumo_Deadlift",
  "t-bar-row": "Lying_T-Bar_Row",
  "triceps-pushdown": "Triceps_Pushdown_-_Rope_Attachment",
  "upright-row": "Upright_Barbell_Row",
  "walking-lunge": "Dumbbell_Lunges",
  "wide-grip-pull-up": "Wide-Grip_Rear_Pull-Up",
  "wrist-curl": "Cable_Wrist_Curl",
  "zottman-curl": "Zottman_Curl",
};

const CDN = "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises";

/** 시연 사진 2프레임 URL. 매핑 없으면 null → 호출부가 SVG 폴백. */
export function exercisePhotoFrames(exerciseId: string): [string, string] | null {
  const db = EXERCISE_PHOTO_DB[exerciseId];
  if (!db) return null;
  return [`${CDN}/${db}/0.jpg`, `${CDN}/${db}/1.jpg`];
}
